using System.Globalization;

namespace KeorMon.UI;

/// <summary>
/// Lightweight localization for the 20 most spoken languages.
/// Each key maps to an array of translations in the fixed order of <see cref="Codes"/>;
/// lookup falls back to English (index 0) when a language or key is missing.
/// Set the language explicitly via <see cref="Initialize"/> ("auto" follows the OS).
/// </summary>
public static class L10n
{
    /// <summary>ISO 639-1 codes, fixed order. en, it first for readability; the rest by speakers.</summary>
    public static readonly string[] Codes =
        { "en", "it", "zh", "hi", "es", "fr", "ar", "bn", "pt", "ru", "ur", "id", "de", "ja", "mr", "te", "tr", "ta", "vi", "ko" };

    /// <summary>Native display names, same order as <see cref="Codes"/>.</summary>
    public static readonly string[] NativeNames =
        { "English", "Italiano", "中文", "हिन्दी", "Español", "Français", "العربية", "বাংলা", "Português", "Русский",
          "اردو", "Bahasa Indonesia", "Deutsch", "日本語", "मराठी", "తెలుగు", "Türkçe", "தமிழ்", "Tiếng Việt", "한국어" };

    private static int _lang;   // index into Codes

    public static void Initialize(string language)
    {
        var code = string.IsNullOrWhiteSpace(language) || language == "auto"
            ? CultureInfo.CurrentUICulture.TwoLetterISOLanguageName
            : language;
        _lang = Math.Max(0, Array.IndexOf(Codes, code));
    }

    public static string T(string key)
    {
        if (!S.TryGetValue(key, out var arr)) return key;
        var v = _lang < arr.Length ? arr[_lang] : null;
        return string.IsNullOrEmpty(v) ? arr[0] : v;
    }

    public static string F(string key, params object?[] args) => string.Format(T(key), args);

    // ------------------------------------------------------------------------
    // order: en, it, zh, hi, es, fr, ar, bn, pt, ru, ur, id, de, ja, mr, te, tr, ta, vi, ko
    private static readonly Dictionary<string, string[]> S = new()
    {
        ["tab_synoptic"] = new[] { "Synoptic", "Sinottico", "系统图", "सिनॉप्टिक", "Sinóptico", "Synoptique", "مخطط", "সিনপটিক", "Sinóptico", "Схема", "خاکہ", "Sinoptik", "Übersicht", "系統図", "सिनॉप्टिक", "సినాప్టిక్", "Şema", "சினாப்டிக்", "Sơ đồ", "개요도" },
        ["tab_dashboard"] = new[] { "Dashboard", "Dashboard", "仪表板", "डैशबोर्ड", "Panel", "Tableau de bord", "لوحة", "ড্যাশবোর্ড", "Painel", "Панель", "ڈیش بورڈ", "Dasbor", "Dashboard", "ダッシュボード", "डॅशबोर्ड", "డాష్‌బోర్డ్", "Panel", "டாஷ்போர்டு", "Bảng điều khiển", "대시보드" },
        ["tab_events"] = new[] { "Events", "Eventi", "事件", "घटनाएँ", "Eventos", "Événements", "أحداث", "ইভেন্ট", "Eventos", "События", "واقعات", "Peristiwa", "Ereignisse", "イベント", "घटना", "ఈవెంట్లు", "Olaylar", "நிகழ்வுகள்", "Sự kiện", "이벤트" },
        ["tab_settings"] = new[] { "Settings", "Impostazioni", "设置", "सेटिंग्स", "Ajustes", "Paramètres", "إعدادات", "সেটিংস", "Configurações", "Настройки", "ترتیبات", "Pengaturan", "Einstellungen", "設定", "सेटिंग्ज", "సెట్టింగ్‌లు", "Ayarlar", "அமைப்புகள்", "Cài đặt", "설정" },

        ["card_power"] = new[] { "Power source", "Alimentazione", "电源", "पावर स्रोत", "Alimentación", "Alimentation", "مصدر الطاقة", "পাওয়ার উৎস", "Alimentação", "Питание", "پاور ذریعہ", "Sumber daya", "Stromquelle", "電源", "वीज स्रोत", "విద్యుత్ మూలం", "Güç kaynağı", "மின் மூலம்", "Nguồn điện", "전원" },
        ["card_charge"] = new[] { "Battery charge", "Carica batteria", "电池电量", "बैटरी चार्ज", "Carga batería", "Charge batterie", "شحن البطارية", "ব্যাটারি চার্জ", "Carga da bateria", "Заряд батареи", "بیٹری چارج", "Daya baterai", "Akkuladung", "バッテリー残量", "बॅटरी चार्ज", "బ్యాటరీ ఛార్జ్", "Pil şarjı", "மின்கல சார்ஜ்", "Pin", "배터리 충전" },
        ["card_runtime"] = new[] { "Runtime", "Autonomia", "续航时间", "बैकअप समय", "Autonomía", "Autonomie", "زمن التشغيل", "ব্যাকআপ সময়", "Autonomia", "Время работы", "بیک اپ وقت", "Waktu cadangan", "Restlaufzeit", "稼働時間", "बॅकअप वेळ", "బ్యాకప్ సమయం", "Çalışma süresi", "இயக்க நேரம்", "Thời gian dự phòng", "잔여 시간" },
        ["card_load"] = new[] { "Load", "Carico", "负载", "लोड", "Carga", "Charge", "الحمل", "লোড", "Carga", "Нагрузка", "لوڈ", "Beban", "Last", "負荷", "लोड", "లోడ్", "Yük", "சுமை", "Tải", "부하" },
        ["card_input"] = new[] { "Input", "Ingresso", "输入", "इनपुट", "Entrada", "Entrée", "دخل", "ইনপুট", "Entrada", "Вход", "ان پٹ", "Masukan", "Eingang", "入力", "इनपुट", "ఇన్‌పుట్", "Giriş", "உள்ளீடு", "Đầu vào", "입력" },
        ["card_output"] = new[] { "Output", "Uscita", "输出", "आउटपुट", "Salida", "Sortie", "خرج", "আউটপুট", "Saída", "Выход", "آؤٹ پٹ", "Keluaran", "Ausgang", "出力", "आउटपुट", "అవుట్‌పుట్", "Çıkış", "வெளியீடு", "Đầu ra", "출력" },
        ["card_battery"] = new[] { "Battery", "Batteria", "电池", "बैटरी", "Batería", "Batterie", "البطارية", "ব্যাটারি", "Bateria", "Батарея", "بیٹری", "Baterai", "Akku", "バッテリー", "बॅटरी", "బ్యాటరీ", "Pil", "மின்கலம்", "Pin", "배터리" },
        ["card_watts"] = new[] { "Power", "Potenza", "功率", "पावर", "Potencia", "Puissance", "القدرة", "শক্তি", "Potência", "Мощность", "پاور", "Daya", "Leistung", "電力", "पॉवर", "పవర్", "Güç", "மின்திறன்", "Công suất", "전력" },

        ["sub_charge"] = new[] { "remaining charge", "carica residua", "剩余电量", "शेष चार्ज", "carga restante", "charge restante", "الشحن المتبقي", "অবশিষ্ট চার্জ", "carga restante", "остаток заряда", "باقی چارج", "sisa daya", "Restladung", "残量", "उर्वरित चार्ज", "మిగిలిన ఛార్జ్", "kalan şarj", "மீதமுள்ள சார்ஜ்", "còn lại", "잔여 충전량" },
        ["sub_runtime"] = new[] { "at current load", "a pieno carico attuale", "当前负载下", "वर्तमान लोड पर", "con carga actual", "à la charge actuelle", "بالحمل الحالي", "বর্তমান লোডে", "na carga atual", "при текущей нагрузке", "موجودہ لوڈ پر", "pada beban saat ini", "bei aktueller Last", "現在の負荷で", "सध्याच्या लोडवर", "ప్రస్తుత లోడ్ వద్ద", "mevcut yükte", "தற்போதைய சுமையில்", "với tải hiện tại", "현재 부하 기준" },
        ["sub_of_va"] = new[] { "of {0} VA", "di {0} VA", "共 {0} VA", "{0} VA में से", "de {0} VA", "sur {0} VA", "من {0} VA", "{0} VA এর মধ্যে", "de {0} VA", "из {0} ВА", "{0} VA میں سے", "dari {0} VA", "von {0} VA", "/ {0} VA", "{0} VA पैकी", "{0} VAలో", "{0} VA içinde", "{0} VAல்", "trên {0} VA", "{0} VA 중" },
        ["sub_battv"] = new[] { "battery voltage", "tensione batteria", "电池电压", "बैटरी वोल्टेज", "tensión batería", "tension batterie", "جهد البطارية", "ব্যাটারি ভোল্টেজ", "tensão da bateria", "напряжение батареи", "بیٹری وولٹیج", "tegangan baterai", "Akkuspannung", "バッテリー電圧", "बॅटरी व्होल्टेज", "బ్యాటరీ వోల్టేజ్", "pil gerilimi", "மின்கல மின்னழுத்தம்", "điện áp pin", "배터리 전압" },

        ["mains"] = new[] { "MAINS", "RETE", "市电", "मेन", "RED", "SECTEUR", "الكهرباء", "মেইনস", "REDE", "СЕТЬ", "مینز", "PLN", "NETZ", "商用電源", "मेन", "మెయిన్స్", "ŞEBEKE", "மின்சாரம்", "LƯỚI ĐIỆN", "상용전원" },
        ["battery"] = new[] { "BATTERY", "BATTERIA", "电池", "बैटरी", "BATERÍA", "BATTERIE", "البطارية", "ব্যাটারি", "BATERIA", "БАТАРЕЯ", "بیٹری", "BATERAI", "AKKU", "バッテリー", "बॅटरी", "బ్యాటరీ", "PİL", "மின்கலம்", "PIN", "배터리" },

        ["status_normal"] = new[] { "normal operation", "funzionamento normale", "运行正常", "सामान्य संचालन", "funcionamiento normal", "fonctionnement normal", "تشغيل طبيعي", "স্বাভাবিক অপারেশন", "operação normal", "нормальная работа", "معمول کارکردگی", "operasi normal", "Normalbetrieb", "正常動作", "सामान्य कार्य", "సాధారణ పనితీరు", "normal çalışma", "இயல்பான இயக்கம்", "hoạt động bình thường", "정상 작동" },
        ["status_service"] = new[] { "[service active]", "[servizio attivo]", "[服务运行中]", "[सेवा सक्रिय]", "[servicio activo]", "[service actif]", "[الخدمة نشطة]", "[পরিষেবা সক্রিয়]", "[serviço ativo]", "[служба активна]", "[سروس فعال]", "[layanan aktif]", "[Dienst aktiv]", "[サービス稼働中]", "[सेवा सक्रिय]", "[సర్వీస్ యాక్టివ్]", "[hizmet etkin]", "[சேவை இயக்கத்தில்]", "[dịch vụ đang chạy]", "[서비스 활성]" },
        ["status_waiting"] = new[] { "Waiting for first reading…", "In attesa della prima lettura…", "等待首次读取…", "पहली रीडिंग की प्रतीक्षा…", "Esperando primera lectura…", "En attente de la première lecture…", "بانتظار أول قراءة…", "প্রথম রিডিংয়ের অপেক্ষায়…", "Aguardando primeira leitura…", "Ожидание первого чтения…", "پہلی ریڈنگ کا انتظار…", "Menunggu pembacaan pertama…", "Warte auf erste Messung…", "初回読み取り待ち…", "पहिल्या वाचनाची प्रतीक्षा…", "మొదటి రీడింగ్ కోసం వేచి…", "İlk okuma bekleniyor…", "முதல் வாசிப்புக்காக காத்திருக்கிறது…", "Đang chờ lần đọc đầu…", "첫 판독 대기 중…" },
        ["status_nodata"] = new[] { "Waiting for UPS data…", "In attesa di dati dal UPS…", "等待UPS数据…", "UPS डेटा की प्रतीक्षा…", "Esperando datos del SAI…", "En attente des données de l'onduleur…", "بانتظار بيانات UPS…", "UPS ডেটার অপেক্ষায়…", "Aguardando dados do UPS…", "Ожидание данных ИБП…", "UPS ڈیٹا کا انتظار…", "Menunggu data UPS…", "Warte auf USV-Daten…", "UPSデータ待ち…", "UPS डेटाची प्रतीक्षा…", "UPS డేటా కోసం వేచి…", "UPS verisi bekleniyor…", "UPS தரவுக்காக காத்திருக்கிறது…", "Đang chờ dữ liệu UPS…", "UPS 데이터 대기 중…" },

        ["period"] = new[] { "Period:", "Periodo:", "时段：", "अवधि:", "Período:", "Période :", "الفترة:", "সময়কাল:", "Período:", "Период:", "مدت:", "Periode:", "Zeitraum:", "期間：", "कालावधी:", "వ్యవధి:", "Dönem:", "காலம்:", "Khoảng thời gian:", "기간:" },
        ["range_10m"] = new[] { "Last 10 minutes", "Ultimi 10 minuti", "最近10分钟", "पिछले 10 मिनट", "Últimos 10 minutos", "10 dernières minutes", "آخر 10 دقائق", "গত ১০ মিনিট", "Últimos 10 minutos", "Последние 10 минут", "پچھلے 10 منٹ", "10 menit terakhir", "Letzte 10 Minuten", "直近10分", "मागील 10 मिनिटे", "గత 10 నిమిషాలు", "Son 10 dakika", "கடந்த 10 நிமிடங்கள்", "10 phút qua", "지난 10분" },
        ["range_1h"] = new[] { "Last hour", "Ultima ora", "最近1小时", "पिछला घंटा", "Última hora", "Dernière heure", "آخر ساعة", "গত ঘণ্টা", "Última hora", "Последний час", "پچھلا گھنٹہ", "1 jam terakhir", "Letzte Stunde", "直近1時間", "मागील तास", "గత గంట", "Son 1 saat", "கடந்த மணி", "1 giờ qua", "지난 1시간" },
        ["range_6h"] = new[] { "Last 6 hours", "Ultime 6 ore", "最近6小时", "पिछले 6 घंटे", "Últimas 6 horas", "6 dernières heures", "آخر 6 ساعات", "গত ৬ ঘণ্টা", "Últimas 6 horas", "Последние 6 часов", "پچھلے 6 گھنٹے", "6 jam terakhir", "Letzte 6 Stunden", "直近6時間", "मागील 6 तास", "గత 6 గంటలు", "Son 6 saat", "கடந்த 6 மணி", "6 giờ qua", "지난 6시간" },
        ["range_24h"] = new[] { "Last 24 hours", "Ultime 24 ore", "最近24小时", "पिछले 24 घंटे", "Últimas 24 horas", "24 dernières heures", "آخر 24 ساعة", "গত ২৪ ঘণ্টা", "Últimas 24 horas", "Последние 24 часа", "پچھلے 24 گھنٹے", "24 jam terakhir", "Letzte 24 Stunden", "直近24時間", "मागील 24 तास", "గత 24 గంటలు", "Son 24 saat", "கடந்த 24 மணி", "24 giờ qua", "지난 24시간" },
        ["range_7d"] = new[] { "Last 7 days", "Ultimi 7 giorni", "最近7天", "पिछले 7 दिन", "Últimos 7 días", "7 derniers jours", "آخر 7 أيام", "গত ৭ দিন", "Últimos 7 dias", "Последние 7 дней", "پچھلے 7 دن", "7 hari terakhir", "Letzte 7 Tage", "直近7日", "मागील 7 दिवस", "గత 7 రోజులు", "Son 7 gün", "கடந்த 7 நாட்கள்", "7 ngày qua", "지난 7일" },
        ["range_30d"] = new[] { "Last 30 days", "Ultimi 30 giorni", "最近30天", "पिछले 30 दिन", "Últimos 30 días", "30 derniers jours", "آخر 30 يومًا", "গত ৩০ দিন", "Últimos 30 dias", "Последние 30 дней", "پچھلے 30 دن", "30 hari terakhir", "Letzte 30 Tage", "直近30日", "मागील 30 दिवस", "గత 30 రోజులు", "Son 30 gün", "கடந்த 30 நாட்கள்", "30 ngày qua", "지난 30일" },

        ["chart_voltage"] = new[] { "Mains / output voltage (V)", "Tensione rete / uscita (V)", "市电/输出电压 (V)", "मेन/आउटपुट वोल्टेज (V)", "Tensión red / salida (V)", "Tension secteur / sortie (V)", "جهد الكهرباء/الخرج (V)", "মেইনস/আউটপুট ভোল্টেজ (V)", "Tensão rede / saída (V)", "Напряжение сеть/выход (В)", "مینز/آؤٹ پٹ وولٹیج (V)", "Tegangan PLN/keluaran (V)", "Netz-/Ausgangsspannung (V)", "入力/出力電圧 (V)", "मेन/आउटपुट व्होल्टेज (V)", "మెయిన్స్/అవుట్‌పుట్ వోల్టేజ్ (V)", "Şebeke/çıkış gerilimi (V)", "மின்/வெளியீட்டு மின்னழுத்தம் (V)", "Điện áp lưới/ra (V)", "입력/출력 전압 (V)" },
        ["chart_load"] = new[] { "Load and power", "Carico e potenza", "负载与功率", "लोड और पावर", "Carga y potencia", "Charge et puissance", "الحمل والقدرة", "লোড ও শক্তি", "Carga e potência", "Нагрузка и мощность", "لوڈ اور پاور", "Beban dan daya", "Last und Leistung", "負荷と電力", "लोड आणि पॉवर", "లోడ్ & పవర్", "Yük ve güç", "சுமை & திறன்", "Tải và công suất", "부하 및 전력" },
        ["chart_battery"] = new[] { "Battery", "Batteria", "电池", "बैटरी", "Batería", "Batterie", "البطارية", "ব্যাটারি", "Bateria", "Батарея", "بیٹری", "Baterai", "Akku", "バッテリー", "बॅटरी", "బ్యాటరీ", "Pil", "மின்கலம்", "Pin", "배터리" },
        ["chart_runtime"] = new[] { "Estimated runtime (min)", "Autonomia stimata (min)", "预计续航 (分钟)", "अनुमानित बैकअप (मिनट)", "Autonomía estimada (min)", "Autonomie estimée (min)", "زمن التشغيل المقدر (دقيقة)", "আনুমানিক ব্যাকআপ (মিনিট)", "Autonomia estimada (min)", "Оценочное время (мин)", "تخمینی بیک اپ (منٹ)", "Perkiraan cadangan (menit)", "Geschätzte Laufzeit (Min)", "推定稼働時間 (分)", "अंदाजे बॅकअप (मिनिटे)", "అంచనా బ్యాకప్ (నిమి)", "Tahmini süre (dk)", "மதிப்பீட்டு நேரம் (நிமி)", "Thời gian ước tính (phút)", "예상 시간 (분)" },
        ["series_input"] = new[] { "Input", "Ingresso", "输入", "इनपुट", "Entrada", "Entrée", "دخل", "ইনপুট", "Entrada", "Вход", "ان پٹ", "Masukan", "Eingang", "入力", "इनपुट", "ఇన్‌పుట్", "Giriş", "உள்ளீடு", "Vào", "입력" },
        ["series_output"] = new[] { "Output", "Uscita", "输出", "आउटपुट", "Salida", "Sortie", "خرج", "আউটপুট", "Saída", "Выход", "آؤٹ پٹ", "Keluaran", "Ausgang", "出力", "आउटपुट", "అవుట్‌పుట్", "Çıkış", "வெளியீடு", "Ra", "출력" },
        ["series_load"] = new[] { "Load %", "Carico %", "负载 %", "लोड %", "Carga %", "Charge %", "الحمل %", "লোড %", "Carga %", "Нагрузка %", "لوڈ %", "Beban %", "Last %", "負荷 %", "लोड %", "లోడ్ %", "Yük %", "சுமை %", "Tải %", "부하 %" },
        ["series_watts"] = new[] { "Power W", "Potenza W", "功率 W", "पावर W", "Potencia W", "Puissance W", "القدرة W", "শক্তি W", "Potência W", "Мощность Вт", "پاور W", "Daya W", "Leistung W", "電力 W", "पॉवर W", "పవర్ W", "Güç W", "திறன் W", "Công suất W", "전력 W" },
        ["series_charge"] = new[] { "Charge %", "Carica %", "电量 %", "चार्ज %", "Carga %", "Charge %", "الشحن %", "চার্জ %", "Carga %", "Заряд %", "چارج %", "Daya %", "Ladung %", "残量 %", "चार्ज %", "ఛార్జ్ %", "Şarj %", "சார்ஜ் %", "Pin %", "충전 %" },
        ["series_battv"] = new[] { "Voltage ×10", "Tensione ×10", "电压 ×10", "वोल्टेज ×10", "Tensión ×10", "Tension ×10", "الجهد ×10", "ভোল্টেজ ×10", "Tensão ×10", "Напряжение ×10", "وولٹیج ×10", "Tegangan ×10", "Spannung ×10", "電圧 ×10", "व्होल्टेज ×10", "వోల్టేజ్ ×10", "Gerilim ×10", "மின்னழுத்தம் ×10", "Điện áp ×10", "전압 ×10" },
        ["series_runtime"] = new[] { "Runtime", "Autonomia", "续航", "बैकअप", "Autonomía", "Autonomie", "زمن التشغيل", "ব্যাকআপ", "Autonomia", "Время", "بیک اپ", "Cadangan", "Laufzeit", "稼働時間", "बॅकअप", "బ్యాకప్", "Süre", "நேரம்", "Thời gian", "시간" },
        ["chart_nodata"] = new[] { "no data in this period", "nessun dato nel periodo", "该时段无数据", "इस अवधि में कोई डेटा नहीं", "sin datos en el período", "aucune donnée sur la période", "لا بيانات في هذه الفترة", "এই সময়ে কোনো ডেটা নেই", "sem dados no período", "нет данных за период", "اس مدت میں کوئی ڈیٹا نہیں", "tidak ada data pada periode ini", "keine Daten im Zeitraum", "この期間のデータなし", "या कालावधीत डेटा नाही", "ఈ వ్యవధిలో డేటా లేదు", "bu dönemde veri yok", "இக்காலத்தில் தரவு இல்லை", "không có dữ liệu", "해당 기간 데이터 없음" },

        ["ev_when"] = new[] { "When", "Quando", "时间", "कब", "Cuándo", "Quand", "متى", "কখন", "Quando", "Когда", "کب", "Kapan", "Wann", "日時", "केव्हा", "ఎప్పుడు", "Ne zaman", "எப்போது", "Khi nào", "일시" },
        ["ev_kind"] = new[] { "Type", "Tipo", "类型", "प्रकार", "Tipo", "Type", "النوع", "ধরন", "Tipo", "Тип", "قسم", "Jenis", "Typ", "種類", "प्रकार", "రకం", "Tür", "வகை", "Loại", "유형" },
        ["ev_message"] = new[] { "Message", "Messaggio", "消息", "संदेश", "Mensaje", "Message", "الرسالة", "বার্তা", "Mensagem", "Сообщение", "پیغام", "Pesan", "Meldung", "メッセージ", "संदेश", "సందేశం", "Mesaj", "செய்தி", "Thông báo", "메시지" },

        ["set_group_monitor"] = new[] { "Monitor thresholds and actions", "Soglie monitor e azioni", "监控阈值与操作", "मॉनिटर सीमाएँ और क्रियाएँ", "Umbrales y acciones", "Seuils et actions", "العتبات والإجراءات", "মনিটর সীমা ও কাজ", "Limites e ações", "Пороги и действия", "مانیٹر حدیں اور اقدامات", "Ambang dan tindakan", "Schwellwerte und Aktionen", "しきい値とアクション", "मर्यादा आणि क्रिया", "పరిమితులు & చర్యలు", "Eşikler ve eylemler", "வரம்புகள் & செயல்கள்", "Ngưỡng và hành động", "임계값 및 동작" },
        ["set_poll"] = new[] { "Poll interval (s)", "Intervallo lettura (s)", "读取间隔 (秒)", "रीडिंग अंतराल (से)", "Intervalo de lectura (s)", "Intervalle de lecture (s)", "فاصل القراءة (ث)", "রিডিং বিরতি (সে)", "Intervalo de leitura (s)", "Интервал опроса (с)", "ریڈنگ وقفہ (س)", "Interval baca (dtk)", "Abfrageintervall (s)", "読み取り間隔 (秒)", "वाचन अंतराल (से)", "రీడింగ్ విరామం (సె)", "Okuma aralığı (sn)", "வாசிப்பு இடைவெளி (வி)", "Chu kỳ đọc (giây)", "판독 간격 (초)" },
        ["set_warn_charge"] = new[] { "Warning: charge ≤ (%)", "Avviso: carica ≤ (%)", "警告：电量 ≤ (%)", "चेतावनी: चार्ज ≤ (%)", "Aviso: carga ≤ (%)", "Alerte : charge ≤ (%)", "تحذير: الشحن ≤ (%)", "সতর্কতা: চার্জ ≤ (%)", "Aviso: carga ≤ (%)", "Внимание: заряд ≤ (%)", "انتباہ: چارج ≤ (%)", "Peringatan: daya ≤ (%)", "Warnung: Ladung ≤ (%)", "警告：残量 ≤ (%)", "इशारा: चार्ज ≤ (%)", "హెచ్చరిక: ఛార్జ్ ≤ (%)", "Uyarı: şarj ≤ (%)", "எச்சரிக்கை: சார்ஜ் ≤ (%)", "Cảnh báo: pin ≤ (%)", "경고: 충전 ≤ (%)" },
        ["set_warn_rt"] = new[] { "Warning: runtime ≤ (s)", "Avviso: autonomia ≤ (s)", "警告：续航 ≤ (秒)", "चेतावनी: बैकअप ≤ (से)", "Aviso: autonomía ≤ (s)", "Alerte : autonomie ≤ (s)", "تحذير: زمن التشغيل ≤ (ث)", "সতর্কতা: ব্যাকআপ ≤ (সে)", "Aviso: autonomia ≤ (s)", "Внимание: время ≤ (с)", "انتباہ: بیک اپ ≤ (س)", "Peringatan: cadangan ≤ (dtk)", "Warnung: Laufzeit ≤ (s)", "警告：稼働 ≤ (秒)", "इशारा: बॅकअप ≤ (से)", "హెచ్చరిక: బ్యాకప్ ≤ (సె)", "Uyarı: süre ≤ (sn)", "எச்சரிக்கை: நேரம் ≤ (வி)", "Cảnh báo: thời gian ≤ (giây)", "경고: 시간 ≤ (초)" },
        ["set_crit_charge"] = new[] { "Critical: charge ≤ (%)", "Critico: carica ≤ (%)", "危急：电量 ≤ (%)", "गंभीर: चार्ज ≤ (%)", "Crítico: carga ≤ (%)", "Critique : charge ≤ (%)", "حرج: الشحن ≤ (%)", "সংকটজনক: চার্জ ≤ (%)", "Crítico: carga ≤ (%)", "Критично: заряд ≤ (%)", "نازک: چارج ≤ (%)", "Kritis: daya ≤ (%)", "Kritisch: Ladung ≤ (%)", "重大：残量 ≤ (%)", "गंभीर: चार्ज ≤ (%)", "క్రిటికల్: ఛార్జ్ ≤ (%)", "Kritik: şarj ≤ (%)", "நெருக்கடி: சார்ஜ் ≤ (%)", "Nguy cấp: pin ≤ (%)", "위험: 충전 ≤ (%)" },
        ["set_crit_rt"] = new[] { "Critical: runtime ≤ (s)", "Critico: autonomia ≤ (s)", "危急：续航 ≤ (秒)", "गंभीर: बैकअप ≤ (से)", "Crítico: autonomía ≤ (s)", "Critique : autonomie ≤ (s)", "حرج: زمن التشغيل ≤ (ث)", "সংকটজনক: ব্যাকআপ ≤ (সে)", "Crítico: autonomia ≤ (s)", "Критично: время ≤ (с)", "نازک: بیک اپ ≤ (س)", "Kritis: cadangan ≤ (dtk)", "Kritisch: Laufzeit ≤ (s)", "重大：稼働 ≤ (秒)", "गंभीर: बॅकअप ≤ (से)", "క్రిటికల్: బ్యాకప్ ≤ (సె)", "Kritik: süre ≤ (sn)", "நெருக்கடி: நேரம் ≤ (வி)", "Nguy cấp: thời gian ≤ (giây)", "위험: 시간 ≤ (초)" },
        ["set_grace"] = new[] { "Delay before hibernating (s)", "Attesa prima di ibernare (s)", "休眠前等待 (秒)", "हाइबरनेट से पहले प्रतीक्षा (से)", "Espera antes de hibernar (s)", "Délai avant hibernation (s)", "المهلة قبل الإسبات (ث)", "হাইবারনেটের আগে অপেক্ষা (সে)", "Espera antes de hibernar (s)", "Задержка перед гибернацией (с)", "ہائبرنیٹ سے پہلے انتظار (س)", "Tunda sebelum hibernasi (dtk)", "Wartezeit vor Ruhezustand (s)", "休止前の待機 (秒)", "हायबरनेटपूर्वी प्रतीक्षा (से)", "హైబర్నేట్ ముందు వేచి (సె)", "Hazırda bekletme öncesi bekleme (sn)", "ஹைபர்நேட் முன் காத்திருப்பு (வி)", "Chờ trước khi ngủ đông (giây)", "최대 절전 전 대기 (초)" },
        ["set_hib_real"] = new[] { "REAL hibernation (unchecked = simulation only)", "Ibernazione REALE (deselezionato = solo simulazione)", "真实休眠（未勾选=仅模拟）", "वास्तविक हाइबरनेशन (अनचेक = केवल सिमुलेशन)", "Hibernación REAL (sin marcar = solo simulación)", "Hibernation RÉELLE (décoché = simulation seule)", "إسبات حقيقي (غير محدد = محاكاة فقط)", "আসল হাইবারনেশন (আনচেক = শুধু সিমুলেশন)", "Hibernação REAL (desmarcado = só simulação)", "РЕАЛЬНАЯ гибернация (снято = только симуляция)", "حقیقی ہائبرنیشن (غیر منتخب = صرف نقل)", "Hibernasi NYATA (tidak dicentang = simulasi saja)", "ECHTER Ruhezustand (deaktiviert = nur Simulation)", "実際に休止する（オフ＝シミュレーションのみ）", "खरे हायबरनेशन (अनचेक = फक्त सिम्युलेशन)", "నిజమైన హైబర్నేషన్ (అన్‌చెక్ = సిమ్యులేషన్ మాత్రమే)", "GERÇEK hazırda beklet (işaretsiz = yalnız simülasyon)", "உண்மையான ஹைபர்நேட் (தேர்வு இல்லை = சிமுலேஷன் மட்டும்)", "Ngủ đông THẬT (bỏ chọn = chỉ mô phỏng)", "실제 최대 절전 (해제 = 시뮬레이션만)" },
        ["set_save"] = new[] { "Save monitor settings", "Salva impostazioni monitor", "保存监控设置", "मॉनिटर सेटिंग्स सहेजें", "Guardar ajustes", "Enregistrer les paramètres", "حفظ الإعدادات", "সেটিংস সংরক্ষণ", "Salvar configurações", "Сохранить настройки", "ترتیبات محفوظ کریں", "Simpan pengaturan", "Einstellungen speichern", "設定を保存", "सेटिंग्ज जतन करा", "సెట్టింగ్‌లు సేవ్ చేయి", "Ayarları kaydet", "அமைப்புகளை சேமி", "Lưu cài đặt", "설정 저장" },
        ["set_test"] = new[] { "Test critical scenario (simulated)", "Prova scenario critico (simulato)", "测试危急场景（模拟）", "गंभीर परिदृश्य परीक्षण (सिमुलेटेड)", "Probar escenario crítico (simulado)", "Tester le scénario critique (simulé)", "اختبار السيناريو الحرج (محاكاة)", "সংকট দৃশ্য পরীক্ষা (সিমুলেটেড)", "Testar cenário crítico (simulado)", "Тест критического сценария (симуляция)", "نازک منظر کی جانچ (نقل)", "Uji skenario kritis (simulasi)", "Kritisches Szenario testen (simuliert)", "危機シナリオをテスト（模擬）", "गंभीर परिस्थिती चाचणी (सिम्युलेटेड)", "క్రిటికల్ దృశ్య పరీక్ష (సిమ్యులేటెడ్)", "Kritik senaryoyu test et (simüle)", "நெருக்கடி சூழலை சோதி (சிமுலேட்டட்)", "Thử kịch bản nguy cấp (mô phỏng)", "위험 시나리오 테스트 (시뮬레이션)" },
        ["set_test_stop"] = new[] { "Stop simulation", "Ferma simulazione", "停止模拟", "सिमुलेशन रोकें", "Detener simulación", "Arrêter la simulation", "إيقاف المحاكاة", "সিমুলেশন বন্ধ", "Parar simulação", "Остановить симуляцию", "نقل روکیں", "Hentikan simulasi", "Simulation stoppen", "シミュレーション停止", "सिम्युलेशन थांबवा", "సిమ్యులేషన్ ఆపు", "Simülasyonu durdur", "சிமுலேஷனை நிறுத்து", "Dừng mô phỏng", "시뮬레이션 중지" },
        ["set_service_note"] = new[] {
            "KeorMon service active: history and hibernation are handled by the service\n(even with no user logged in). Settings saved here are reloaded\nautomatically by the service.",
            "Servizio KeorMon attivo: storico e ibernazione sono gestiti dal servizio\n(anche senza utente collegato). Le impostazioni salvate qui vengono\nricaricate automaticamente dal servizio.",
            "KeorMon 服务运行中：历史记录和休眠由服务处理（即使无人登录）。\n此处保存的设置将由服务自动重新加载。",
            "KeorMon सेवा सक्रिय: इतिहास और हाइबरनेशन सेवा द्वारा संभाले जाते हैं\n(बिना लॉगिन के भी)। यहाँ सहेजी सेटिंग्स सेवा स्वतः पुनः लोड करती है।",
            "Servicio KeorMon activo: el historial y la hibernación los gestiona el servicio\n(incluso sin usuario conectado). Los ajustes guardados aquí se recargan\nautomáticamente.",
            "Service KeorMon actif : l'historique et l'hibernation sont gérés par le service\n(même sans utilisateur connecté). Les paramètres enregistrés ici sont\nrechargés automatiquement.",
            "خدمة KeorMon نشطة: السجل والإسبات تديرهما الخدمة (حتى دون تسجيل دخول).\nالإعدادات المحفوظة هنا يعاد تحميلها تلقائيًا.",
            "KeorMon পরিষেবা সক্রিয়: ইতিহাস ও হাইবারনেশন পরিষেবা পরিচালনা করে\n(লগইন ছাড়াও)। এখানে সংরক্ষিত সেটিংস স্বয়ংক্রিয়ভাবে পুনরায় লোড হয়।",
            "Serviço KeorMon ativo: histórico e hibernação são geridos pelo serviço\n(mesmo sem usuário conectado). As configurações salvas aqui são\nrecarregadas automaticamente.",
            "Служба KeorMon активна: история и гибернация управляются службой\n(даже без входа пользователя). Сохранённые здесь настройки служба\nперезагружает автоматически.",
            "KeorMon سروس فعال: تاریخ اور ہائبرنیشن سروس سنبھالتی ہے (بغیر لاگ اِن بھی)۔\nیہاں محفوظ ترتیبات سروس خودکار دوبارہ لوڈ کرتی ہے۔",
            "Layanan KeorMon aktif: riwayat dan hibernasi ditangani layanan\n(bahkan tanpa pengguna masuk). Pengaturan yang disimpan di sini dimuat\nulang otomatis.",
            "KeorMon-Dienst aktiv: Verlauf und Ruhezustand übernimmt der Dienst\n(auch ohne angemeldeten Benutzer). Hier gespeicherte Einstellungen lädt\nder Dienst automatisch neu.",
            "KeorMonサービス稼働中：履歴と休止はサービスが処理します（未ログインでも）。\nここで保存した設定はサービスが自動で再読み込みします。",
            "KeorMon सेवा सक्रिय: इतिहास व हायबरनेशन सेवा हाताळते (लॉगिनशिवायही)।\nयेथे जतन केलेल्या सेटिंग्ज सेवा आपोआप पुन्हा लोड करते.",
            "KeorMon సర్వీస్ యాక్టివ్: హిస్టరీ & హైబర్నేషన్ సర్వీస్ నిర్వహిస్తుంది\n(లాగిన్ లేకున్నా). ఇక్కడ సేవ్ చేసిన సెట్టింగ్‌లు ఆటోమేటిక్‌గా రీలోడ్ అవుతాయి.",
            "KeorMon hizmeti etkin: geçmiş ve hazırda bekletme hizmet tarafından yönetilir\n(oturum açılmasa bile). Burada kaydedilen ayarlar otomatik yeniden yüklenir.",
            "KeorMon சேவை இயக்கத்தில்: வரலாறு & ஹைபர்நேட் சேவை கையாளுகிறது\n(உள்நுழையாமலும்). இங்கு சேமித்த அமைப்புகள் தானாக மீளேற்றப்படும்.",
            "Dịch vụ KeorMon đang chạy: lịch sử và ngủ đông do dịch vụ xử lý\n(kể cả khi không đăng nhập). Cài đặt lưu ở đây được dịch vụ tự nạp lại.",
            "KeorMon 서비스 활성: 기록과 최대 절전은 서비스가 처리합니다\n(로그인 없이도). 여기서 저장한 설정은 서비스가 자동으로 다시 불러옵니다." },
        ["set_action"] = new[] { "Critical action", "Azione critica", "危急操作", "गंभीर क्रिया", "Acción crítica", "Action critique", "الإجراء الحرج", "সংকট কর্ম", "Ação crítica", "Критическое действие", "نازک اقدام", "Tindakan kritis", "Kritische Aktion", "危機時の動作", "गंभीर क्रिया", "క్రిటికల్ చర్య", "Kritik eylem", "நெருக்கடி செயல்", "Hành động nguy cấp", "위험 시 동작" },
        ["act_simulate"] = new[] { "Simulate only", "Solo simulazione", "仅模拟", "केवल सिमुलेशन", "Solo simulación", "Simulation seule", "محاكاة فقط", "শুধু সিমুলেশন", "Só simulação", "Только симуляция", "صرف نقل", "Hanya simulasi", "Nur Simulation", "シミュレーションのみ", "फक्त सिम्युलेशन", "సిమ్యులేషన్ మాత్రమే", "Yalnız simülasyon", "சிமுலேஷன் மட்டும்", "Chỉ mô phỏng", "시뮬레이션만" },
        ["act_hibernate"] = new[] { "Hibernate PC", "Iberna il PC", "休眠电脑", "PC हाइबरनेट करें", "Hibernar PC", "Mettre le PC en hibernation", "إسبات الحاسوب", "PC হাইবারনেট", "Hibernar PC", "Гибернация ПК", "PC ہائبرنیٹ", "Hibernasi PC", "PC in Ruhezustand", "PCを休止", "PC हायबरनेट", "PC హైబర్నేట్", "PC'yi hazırda beklet", "PC ஹைபர்நேட்", "Ngủ đông PC", "PC 최대 절전" },
        ["act_shutdown"] = new[] { "Shut down PC", "Spegni il PC", "关闭电脑", "PC बंद करें", "Apagar PC", "Éteindre le PC", "إيقاف تشغيل الحاسوب", "PC বন্ধ করুন", "Desligar PC", "Выключить ПК", "PC بند کریں", "Matikan PC", "PC herunterfahren", "PCをシャットダウン", "PC बंद करा", "PC షట్‌డౌన్", "PC'yi kapat", "PC அணை", "Tắt PC", "PC 종료" },
        ["al_shut"] = new[] { "UPS: shutting down now", "UPS: spegnimento in corso", "UPS：正在关机", "UPS: बंद हो रहा", "SAI: apagando ahora", "Onduleur : arrêt en cours", "UPS: جارٍ إيقاف التشغيل", "UPS: বন্ধ হচ্ছে", "UPS: desligando agora", "ИБП: выполняется выключение", "UPS: بند ہو رہا", "UPS: mematikan sekarang", "USV: wird heruntergefahren", "UPS：シャットダウン中", "UPS: बंद होत आहे", "UPS: షట్‌డౌన్ అవుతోంది", "UPS: kapatılıyor", "UPS: அணைக்கப்படுகிறது", "UPS: đang tắt máy", "UPS: 종료 진행 중" },
        ["set_saved2"] = new[] { "Saved {0}. Action: {1}.", "Salvato {0}. Azione: {1}.", "已保存 {0}。操作：{1}。", "सहेजा {0}। क्रिया: {1}।", "Guardado {0}. Acción: {1}.", "Enregistré {0}. Action : {1}.", "تم الحفظ {0}. الإجراء: {1}.", "সংরক্ষিত {0}। কর্ম: {1}।", "Salvo {0}. Ação: {1}.", "Сохранено {0}. Действие: {1}.", "محفوظ {0}۔ اقدام: {1}۔", "Disimpan {0}. Tindakan: {1}.", "Gespeichert {0}. Aktion: {1}.", "保存済み {0}。動作：{1}。", "जतन केले {0}. क्रिया: {1}.", "సేవ్ అయింది {0}. చర్య: {1}.", "Kaydedildi {0}. Eylem: {1}.", "சேமிக்கப்பட்டது {0}. செயல்: {1}.", "Đã lưu {0}. Hành động: {1}.", "저장됨 {0}. 동작: {1}." },
        ["set_confirm_real_body"] = new[] {
            "Enable the REAL action?\n\nWhen the battery reaches the critical threshold, the selected action (hibernate or shut down) will REALLY be executed.",
            "Attivare l'azione REALE?\n\nQuando la batteria raggiunge la soglia critica, l'azione selezionata (ibernazione o spegnimento) verrà eseguita DAVVERO.",
            "启用真实操作？\n\n电池达到危急阈值时，所选操作（休眠或关机）将真正执行。",
            "वास्तविक क्रिया सक्षम करें?\n\nबैटरी गंभीर सीमा पर पहुँचने पर चयनित क्रिया (हाइबरनेट या बंद) वास्तव में निष्पादित होगी।",
            "¿Activar la acción REAL?\n\nCuando la batería alcance el umbral crítico, la acción seleccionada (hibernar o apagar) se ejecutará DE VERDAD.",
            "Activer l'action RÉELLE ?\n\nQuand la batterie atteindra le seuil critique, l'action sélectionnée (hibernation ou arrêt) sera VRAIMENT exécutée.",
            "تفعيل الإجراء الحقيقي؟\n\nعند وصول البطارية إلى العتبة الحرجة سيُنفذ الإجراء المحدد (إسبات أو إيقاف) فعلاً.",
            "আসল কর্ম চালু করবেন?\n\nব্যাটারি সংকট সীমায় পৌঁছালে নির্বাচিত কর্ম (হাইবারনেট বা বন্ধ) সত্যিই সম্পাদিত হবে।",
            "Ativar a ação REAL?\n\nQuando a bateria atingir o limite crítico, a ação selecionada (hibernar ou desligar) será REALMENTE executada.",
            "Включить РЕАЛЬНОЕ действие?\n\nПри достижении критического порога выбранное действие (гибернация или выключение) будет выполнено НА САМОМ ДЕЛЕ.",
            "حقیقی اقدام فعال کریں؟\n\nبیٹری نازک حد پر پہنچنے پر منتخب اقدام (ہائبرنیٹ یا بند) واقعی انجام پائے گا۔",
            "Aktifkan tindakan NYATA?\n\nSaat baterai mencapai ambang kritis, tindakan terpilih (hibernasi atau matikan) BENAR-BENAR dijalankan.",
            "ECHTE Aktion aktivieren?\n\nErreicht der Akku die kritische Schwelle, wird die gewählte Aktion (Ruhezustand oder Herunterfahren) WIRKLICH ausgeführt.",
            "実際の動作を有効にしますか？\n\nバッテリーが危険しきい値に達すると、選択した動作（休止またはシャットダウン）が本当に実行されます。",
            "खरी क्रिया सुरू करायची?\n\nबॅटरी गंभीर मर्यादेवर पोहोचल्यावर निवडलेली क्रिया (हायबरनेट किंवा बंद) खरोखर अंमलात येईल.",
            "నిజమైన చర్యను ఆన్ చేయాలా?\n\nబ్యాటరీ క్రిటికల్ స్థాయికి చేరితే ఎంచుకున్న చర్య (హైబర్నేట్ లేదా షట్‌డౌన్) నిజంగా అమలవుతుంది.",
            "GERÇEK eylem etkinleştirilsin mi?\n\nPil kritik eşiğe ulaştığında seçilen eylem (hazırda beklet veya kapat) GERÇEKTEN uygulanacak.",
            "உண்மையான செயலை இயக்கவா?\n\nமின்கலம் நெருக்கடி வரம்பை அடைந்தால் தேர்ந்த செயல் (ஹைபர்நேட் அல்லது அணைத்தல்) உண்மையில் நடக்கும்.",
            "Bật hành động THẬT?\n\nKhi pin chạm ngưỡng nguy cấp, hành động đã chọn (ngủ đông hoặc tắt máy) sẽ THỰC SỰ được thực hiện.",
            "실제 동작을 활성화할까요?\n\n배터리가 위험 임계값에 도달하면 선택한 동작(최대 절전 또는 종료)이 실제로 실행됩니다." },
        ["set_confirm_title"] = new[] { "Confirm real hibernation", "Conferma ibernazione reale", "确认真实休眠", "वास्तविक हाइबरनेशन की पुष्टि", "Confirmar hibernación real", "Confirmer l'hibernation réelle", "تأكيد الإسبات الحقيقي", "আসল হাইবারনেশন নিশ্চিত", "Confirmar hibernação real", "Подтвердите реальную гибернацию", "حقیقی ہائبرنیشن کی تصدیق", "Konfirmasi hibernasi nyata", "Echten Ruhezustand bestätigen", "実休止の確認", "खऱ्या हायबरनेशनची पुष्टी", "నిజమైన హైబర్నేషన్ నిర్ధారణ", "Gerçek hazırda bekletmeyi onayla", "உண்மை ஹைபர்நேட் உறுதி", "Xác nhận ngủ đông thật", "실제 최대 절전 확인" },
        ["set_confirm_body"] = new[] {
            "Enable REAL hibernation?\n\nWhen the battery reaches the critical threshold the PC will really hibernate.",
            "Attivare l'ibernazione REALE?\n\nQuando la batteria raggiunge la soglia critica il PC verrà ibernato davvero.",
            "启用真实休眠？\n\n电池达到危急阈值时，电脑将真正进入休眠。",
            "वास्तविक हाइबरनेशन सक्षम करें?\n\nबैटरी गंभीर सीमा पर पहुँचने पर PC वास्तव में हाइबरनेट होगा।",
            "¿Activar la hibernación REAL?\n\nCuando la batería alcance el umbral crítico, el PC hibernará de verdad.",
            "Activer l'hibernation RÉELLE ?\n\nQuand la batterie atteindra le seuil critique, le PC hibernera vraiment.",
            "تفعيل الإسبات الحقيقي؟\n\nعند وصول البطارية إلى العتبة الحرجة سيدخل الحاسوب في الإسبات فعلاً.",
            "আসল হাইবারনেশন চালু করবেন?\n\nব্যাটারি সংকট সীমায় পৌঁছালে PC সত্যিই হাইবারনেট হবে।",
            "Ativar hibernação REAL?\n\nQuando a bateria atingir o limite crítico o PC hibernará de verdade.",
            "Включить РЕАЛЬНУЮ гибернацию?\n\nПри достижении критического порога ПК действительно уйдёт в гибернацию.",
            "حقیقی ہائبرنیشن فعال کریں؟\n\nبیٹری نازک حد پر پہنچنے پر PC واقعی ہائبرنیٹ ہوگا۔",
            "Aktifkan hibernasi NYATA?\n\nSaat baterai mencapai ambang kritis, PC benar-benar akan hibernasi.",
            "ECHTEN Ruhezustand aktivieren?\n\nErreicht der Akku die kritische Schwelle, geht der PC wirklich in den Ruhezustand.",
            "実際の休止を有効にしますか？\n\nバッテリーが危険しきい値に達すると、PCは本当に休止します。",
            "खरे हायबरनेशन सुरू करायचे?\n\nबॅटरी गंभीर मर्यादेवर पोहोचल्यावर PC खरोखर हायबरनेट होईल.",
            "నిజమైన హైబర్నేషన్ ఆన్ చేయాలా?\n\nబ్యాటరీ క్రిటికల్ స్థాయికి చేరితే PC నిజంగా హైబర్నేట్ అవుతుంది.",
            "GERÇEK hazırda bekletme etkinleştirilsin mi?\n\nPil kritik eşiğe ulaştığında PC gerçekten hazırda bekletilecek.",
            "உண்மையான ஹைபர்நேட்டை இயக்கவா?\n\nமின்கலம் நெருக்கடி வரம்பை அடைந்தால் PC உண்மையில் ஹைபர்நேட் ஆகும்.",
            "Bật ngủ đông THẬT?\n\nKhi pin chạm ngưỡng nguy cấp, PC sẽ thực sự ngủ đông.",
            "실제 최대 절전을 활성화할까요?\n\n배터리가 위험 임계값에 도달하면 PC가 실제로 최대 절전됩니다." },
        ["set_saved"] = new[] { "Saved {0}. Hibernation: {1}.", "Salvato {0}. Ibernazione: {1}.", "已保存 {0}。休眠：{1}。", "सहेजा {0}। हाइबरनेशन: {1}।", "Guardado {0}. Hibernación: {1}.", "Enregistré {0}. Hibernation : {1}.", "تم الحفظ {0}. الإسبات: {1}.", "সংরক্ষিত {0}। হাইবারনেশন: {1}।", "Salvo {0}. Hibernação: {1}.", "Сохранено {0}. Гибернация: {1}.", "محفوظ {0}۔ ہائبرنیشن: {1}۔", "Disimpan {0}. Hibernasi: {1}.", "Gespeichert {0}. Ruhezustand: {1}.", "保存済み {0}。休止：{1}。", "जतन केले {0}. हायबरनेशन: {1}.", "సేవ్ అయింది {0}. హైబర్నేషన్: {1}.", "Kaydedildi {0}. Hazırda beklet: {1}.", "சேமிக்கப்பட்டது {0}. ஹைபர்நேட்: {1}.", "Đã lưu {0}. Ngủ đông: {1}.", "저장됨 {0}. 최대 절전: {1}." },
        ["hib_real"] = new[] { "REAL", "REALE", "真实", "वास्तविक", "REAL", "RÉELLE", "حقيقي", "আসল", "REAL", "РЕАЛЬНАЯ", "حقیقی", "NYATA", "ECHT", "実行", "खरे", "నిజమైన", "GERÇEK", "உண்மை", "THẬT", "실제" },
        ["hib_sim"] = new[] { "simulated", "simulata", "模拟", "सिमुलेटेड", "simulada", "simulée", "محاكاة", "সিমুলেটেড", "simulada", "симуляция", "نقل", "simulasi", "simuliert", "シミュレーション", "सिम्युलेटेड", "సిమ్యులేటెడ్", "simüle", "சிமுலேட்டட்", "mô phỏng", "시뮬레이션" },
        ["set_sim_on"] = new[] { "Critical simulation active: battery state forced. Hibernation stays simulated unless enabled.", "Simulazione critica attiva: stato batteria forzato. L'ibernazione resta simulata se non abilitata.", "危急模拟已激活：电池状态被强制。除非启用，否则休眠仅为模拟。", "गंभीर सिमुलेशन सक्रिय: बैटरी स्थिति बलपूर्वक। सक्षम न होने पर हाइबरनेशन केवल सिमुलेटेड।", "Simulación crítica activa: estado de batería forzado. La hibernación sigue simulada si no está activada.", "Simulation critique active : état batterie forcé. L'hibernation reste simulée si non activée.", "المحاكاة الحرجة نشطة: حالة البطارية مفروضة. يبقى الإسبات محاكاة ما لم يُفعّل.", "সংকট সিমুলেশন সক্রিয়: ব্যাটারি অবস্থা জোরপূর্বক। সক্ষম না হলে হাইবারনেশন সিমুলেটেড থাকে।", "Simulação crítica ativa: estado da bateria forçado. A hibernação continua simulada se não ativada.", "Критическая симуляция активна: состояние батареи форсировано. Гибернация остаётся симуляцией, если не включена.", "نازک نقل فعال: بیٹری حالت جبری۔ فعال نہ ہونے پر ہائبرنیشن نقل رہے گی۔", "Simulasi kritis aktif: status baterai dipaksa. Hibernasi tetap simulasi jika tidak diaktifkan.", "Kritische Simulation aktiv: Akkuzustand erzwungen. Ruhezustand bleibt simuliert, sofern nicht aktiviert.", "危機シミュレーション有効：バッテリー状態を強制。有効化しない限り休止は模擬のまま。", "गंभीर सिम्युलेशन सक्रिय: बॅटरी स्थिती जबरदस्ती. सक्षम नसल्यास हायबरनेशन सिम्युलेटेडच राहते.", "క్రిటికల్ సిమ్యులేషన్ యాక్టివ్: బ్యాటరీ స్థితి బలవంతం. ఎనేబుల్ చేయకపోతే హైబర్నేషన్ సిమ్యులేటెడ్‌గా ఉంటుంది.", "Kritik simülasyon etkin: pil durumu zorlandı. Etkinleştirilmedikçe hazırda bekletme simüle kalır.", "நெருக்கடி சிமுலேஷன் இயக்கத்தில்: மின்கல நிலை கட்டாயம். இயக்கவில்லை என்றால் ஹைபர்நேட் சிமுலேஷனாகவே இருக்கும்.", "Mô phỏng nguy cấp đang chạy: trạng thái pin bị ép. Ngủ đông vẫn là mô phỏng nếu chưa bật.", "위험 시뮬레이션 활성: 배터리 상태 강제. 활성화하지 않으면 최대 절전은 시뮬레이션 상태 유지." },
        ["set_sim_off"] = new[] { "Simulation stopped.", "Simulazione terminata.", "模拟已停止。", "सिमुलेशन बंद।", "Simulación detenida.", "Simulation arrêtée.", "توقفت المحاكاة.", "সিমুলেশন বন্ধ।", "Simulação parada.", "Симуляция остановлена.", "نقل رک گئی۔", "Simulasi dihentikan.", "Simulation beendet.", "シミュレーション停止。", "सिम्युलेशन थांबले.", "సిమ్యులేషన్ ఆగింది.", "Simülasyon durduruldu.", "சிமுலேஷன் நிறுத்தப்பட்டது.", "Đã dừng mô phỏng.", "시뮬레이션 중지됨." },

        ["set_group_ups"] = new[] { "UPS parameters (written to device)", "Parametri del UPS (scrittura su dispositivo)", "UPS 参数（写入设备）", "UPS पैरामीटर (डिवाइस में लिखे जाते हैं)", "Parámetros del SAI (escritos al dispositivo)", "Paramètres de l'onduleur (écrits sur l'appareil)", "معلمات UPS (تُكتب إلى الجهاز)", "UPS প্যারামিটার (ডিভাইসে লেখা হয়)", "Parâmetros do UPS (gravados no dispositivo)", "Параметры ИБП (записываются в устройство)", "UPS پیرامیٹر (آلے میں لکھے جاتے ہیں)", "Parameter UPS (ditulis ke perangkat)", "USV-Parameter (aufs Gerät geschrieben)", "UPSパラメーター（デバイスへ書き込み）", "UPS पॅरामीटर (डिव्हाइसवर लिहिले जातात)", "UPS పారామితులు (పరికరానికి వ్రాయబడతాయి)", "UPS parametreleri (cihaza yazılır)", "UPS அளவுருக்கள் (சாதனத்தில் எழுதப்படும்)", "Tham số UPS (ghi vào thiết bị)", "UPS 매개변수 (장치에 기록)" },
        ["set_param"] = new[] { "Parameter", "Parametro", "参数", "पैरामीटर", "Parámetro", "Paramètre", "المعلمة", "প্যারামিটার", "Parâmetro", "Параметр", "پیرامیٹر", "Parameter", "Parameter", "パラメーター", "पॅरामीटर", "పారామితి", "Parametre", "அளவுரு", "Tham số", "매개변수" },
        ["set_value"] = new[] { "Value", "Valore", "值", "मान", "Valor", "Valeur", "القيمة", "মান", "Valor", "Значение", "قدر", "Nilai", "Wert", "値", "मूल्य", "విలువ", "Değer", "மதிப்பு", "Giá trị", "값" },
        ["set_read"] = new[] { "Read", "Leggi", "读取", "पढ़ें", "Leer", "Lire", "قراءة", "পড়ুন", "Ler", "Читать", "پڑھیں", "Baca", "Lesen", "読み取り", "वाचा", "చదువు", "Oku", "படி", "Đọc", "읽기" },
        ["set_write"] = new[] { "Write to UPS", "Scrivi sul UPS", "写入 UPS", "UPS में लिखें", "Escribir al SAI", "Écrire sur l'onduleur", "كتابة إلى UPS", "UPS-এ লিখুন", "Gravar no UPS", "Записать в ИБП", "UPS میں لکھیں", "Tulis ke UPS", "Auf USV schreiben", "UPSへ書き込み", "UPS वर लिहा", "UPSకి వ్రాయి", "UPS'e yaz", "UPSல் எழுது", "Ghi vào UPS", "UPS에 쓰기" },
        ["set_param_info"] = new[] { "Report 0x{0:X2} — range {1}..{2} {3}.", "Report 0x{0:X2} — range {1}..{2} {3}.", "报告 0x{0:X2} — 范围 {1}..{2} {3}。", "रिपोर्ट 0x{0:X2} — सीमा {1}..{2} {3}।", "Informe 0x{0:X2} — rango {1}..{2} {3}.", "Rapport 0x{0:X2} — plage {1}..{2} {3}.", "التقرير 0x{0:X2} — النطاق {1}..{2} {3}.", "রিপোর্ট 0x{0:X2} — পরিসর {1}..{2} {3}।", "Relatório 0x{0:X2} — faixa {1}..{2} {3}.", "Отчёт 0x{0:X2} — диапазон {1}..{2} {3}.", "رپورٹ 0x{0:X2} — حد {1}..{2} {3}۔", "Laporan 0x{0:X2} — rentang {1}..{2} {3}.", "Report 0x{0:X2} — Bereich {1}..{2} {3}.", "レポート 0x{0:X2} — 範囲 {1}..{2} {3}。", "रिपोर्ट 0x{0:X2} — श्रेणी {1}..{2} {3}.", "రిపోర్ట్ 0x{0:X2} — పరిధి {1}..{2} {3}.", "Rapor 0x{0:X2} — aralık {1}..{2} {3}.", "அறிக்கை 0x{0:X2} — வரம்பு {1}..{2} {3}.", "Báo cáo 0x{0:X2} — dải {1}..{2} {3}.", "리포트 0x{0:X2} — 범위 {1}..{2} {3}." },
        ["set_param_danger"] = new[] { " ⚠ DANGEROUS: arms the UPS output shutdown.", " ⚠ PERICOLOSO: arma lo spegnimento dell'uscita del UPS.", " ⚠ 危险：将触发 UPS 输出断电。", " ⚠ खतरनाक: UPS आउटपुट शटडाउन सक्रिय करता है।", " ⚠ PELIGROSO: arma el apagado de la salida del SAI.", " ⚠ DANGEREUX : arme la coupure de la sortie de l'onduleur.", " ⚠ خطير: يسلّح إيقاف خرج UPS.", " ⚠ বিপজ্জনক: UPS আউটপুট শাটডাউন সক্রিয় করে।", " ⚠ PERIGOSO: arma o desligamento da saída do UPS.", " ⚠ ОПАСНО: взводит отключение выхода ИБП.", " ⚠ خطرناک: UPS آؤٹ پٹ شٹ ڈاؤن مسلح کرتا ہے۔", " ⚠ BERBAHAYA: mengaktifkan pemadaman keluaran UPS.", " ⚠ GEFÄHRLICH: aktiviert die Abschaltung des USV-Ausgangs.", " ⚠ 危険：UPS出力の遮断を作動させます。", " ⚠ धोकादायक: UPS आउटपुट बंद करणे सक्रिय करते.", " ⚠ ప్రమాదకరం: UPS అవుట్‌పుట్ షట్‌డౌన్ ఆర్మ్ చేస్తుంది.", " ⚠ TEHLİKELİ: UPS çıkış kapatmasını devreye alır.", " ⚠ ஆபத்து: UPS வெளியீட்டு நிறுத்தத்தை இயக்குகிறது.", " ⚠ NGUY HIỂM: kích hoạt ngắt đầu ra UPS.", " ⚠ 위험: UPS 출력 차단을 작동시킵니다." },
        ["set_cur_value"] = new[] { "Current value: {0} {1}", "Valore attuale: {0} {1}", "当前值：{0} {1}", "वर्तमान मान: {0} {1}", "Valor actual: {0} {1}", "Valeur actuelle : {0} {1}", "القيمة الحالية: {0} {1}", "বর্তমান মান: {0} {1}", "Valor atual: {0} {1}", "Текущее значение: {0} {1}", "موجودہ قدر: {0} {1}", "Nilai saat ini: {0} {1}", "Aktueller Wert: {0} {1}", "現在値：{0} {1}", "सध्याचे मूल्य: {0} {1}", "ప్రస్తుత విలువ: {0} {1}", "Geçerli değer: {0} {1}", "தற்போதைய மதிப்பு: {0} {1}", "Giá trị hiện tại: {0} {1}", "현재 값: {0} {1}" },
        ["set_not_set"] = new[] { "Value not set on the device.", "Valore non impostato sul dispositivo.", "设备上未设置该值。", "डिवाइस पर मान सेट नहीं।", "Valor no establecido en el dispositivo.", "Valeur non définie sur l'appareil.", "القيمة غير معيّنة على الجهاز.", "ডিভাইসে মান সেট নেই।", "Valor não definido no dispositivo.", "Значение не задано на устройстве.", "آلے پر قدر مقرر نہیں۔", "Nilai tidak disetel di perangkat.", "Wert am Gerät nicht gesetzt.", "デバイスに値が未設定。", "डिव्हाइसवर मूल्य सेट नाही.", "పరికరంలో విలువ సెట్ కాలేదు.", "Cihazda değer ayarlı değil.", "சாதனத்தில் மதிப்பு அமைக்கப்படவில்லை.", "Chưa đặt giá trị trên thiết bị.", "장치에 값이 설정되지 않음." },
        ["set_read_err"] = new[] { "Read error: {0}", "Errore lettura: {0}", "读取错误：{0}", "पढ़ने में त्रुटि: {0}", "Error de lectura: {0}", "Erreur de lecture : {0}", "خطأ قراءة: {0}", "পড়ার ত্রুটি: {0}", "Erro de leitura: {0}", "Ошибка чтения: {0}", "پڑھنے میں خرابی: {0}", "Galat baca: {0}", "Lesefehler: {0}", "読み取りエラー：{0}", "वाचन त्रुटी: {0}", "రీడ్ లోపం: {0}", "Okuma hatası: {0}", "வாசிப்பு பிழை: {0}", "Lỗi đọc: {0}", "읽기 오류: {0}" },
        ["set_write_confirm_title"] = new[] { "Confirm UPS parameter write", "Conferma scrittura parametro UPS", "确认写入 UPS 参数", "UPS पैरामीटर लेखन की पुष्टि", "Confirmar escritura de parámetro", "Confirmer l'écriture du paramètre", "تأكيد كتابة معلمة UPS", "UPS প্যারামিটার লেখা নিশ্চিত", "Confirmar gravação de parâmetro", "Подтвердите запись параметра", "UPS پیرامیٹر لکھنے کی تصدیق", "Konfirmasi tulis parameter UPS", "Schreiben des USV-Parameters bestätigen", "UPSパラメーター書き込みの確認", "UPS पॅरामीटर लेखन पुष्टी", "UPS పారామితి వ్రాత నిర్ధారణ", "UPS parametre yazmayı onayla", "UPS அளவுரு எழுத்தை உறுதிசெய்", "Xác nhận ghi tham số UPS", "UPS 매개변수 쓰기 확인" },
        ["set_write_confirm"] = new[] { "Write {0} {1} to '{2}' (report 0x{3:X2})?", "Scrivere {0} {1} in '{2}' (report 0x{3:X2})?", "将 {0} {1} 写入 '{2}'（报告 0x{3:X2}）？", "'{2}' में {0} {1} लिखें (रिपोर्ट 0x{3:X2})?", "¿Escribir {0} {1} en '{2}' (informe 0x{3:X2})?", "Écrire {0} {1} dans '{2}' (rapport 0x{3:X2}) ?", "كتابة {0} {1} في '{2}' (التقرير 0x{3:X2})؟", "'{2}'-এ {0} {1} লিখবেন (রিপোর্ট 0x{3:X2})?", "Gravar {0} {1} em '{2}' (relatório 0x{3:X2})?", "Записать {0} {1} в '{2}' (отчёт 0x{3:X2})?", "'{2}' میں {0} {1} لکھیں (رپورٹ 0x{3:X2})؟", "Tulis {0} {1} ke '{2}' (laporan 0x{3:X2})?", "{0} {1} in '{2}' schreiben (Report 0x{3:X2})?", "'{2}' に {0} {1} を書き込みますか（レポート 0x{3:X2}）？", "'{2}' मध्ये {0} {1} लिहायचे (रिपोर्ट 0x{3:X2})?", "'{2}'లో {0} {1} వ్రాయాలా (రిపోర్ట్ 0x{3:X2})?", "'{2}' içine {0} {1} yazılsın mı (rapor 0x{3:X2})?", "'{2}'ல் {0} {1} எழுதவா (அறிக்கை 0x{3:X2})?", "Ghi {0} {1} vào '{2}' (báo cáo 0x{3:X2})?", "'{2}'에 {0} {1} 쓸까요 (리포트 0x{3:X2})?" },
        ["set_write_danger"] = new[] { "⚠ '{0}' ARMS THE OUTPUT SHUTDOWN: the UPS outlets may cut power to everything connected.\n\n", "⚠ '{0}' ARMA LO SPEGNIMENTO DELL'USCITA: le prese del UPS possono togliere corrente a tutto ciò che è collegato.\n\n", "⚠ '{0}' 将触发输出断电：UPS 插座可能切断所有连接设备的电源。\n\n", "⚠ '{0}' आउटपुट शटडाउन सक्रिय करता है: UPS आउटलेट सभी जुड़े उपकरणों की बिजली काट सकते हैं।\n\n", "⚠ '{0}' ARMA EL APAGADO DE LA SALIDA: las tomas del SAI pueden cortar la corriente a todo lo conectado.\n\n", "⚠ '{0}' ARME LA COUPURE DE SORTIE : les prises de l'onduleur peuvent couper l'alimentation de tout ce qui est branché.\n\n", "⚠ '{0}' يسلّح إيقاف الخرج: قد تقطع مآخذ UPS الطاقة عن كل ما هو موصول.\n\n", "⚠ '{0}' আউটপুট শাটডাউন সক্রিয় করে: UPS আউটলেট সংযুক্ত সবকিছুর বিদ্যুৎ কেটে দিতে পারে।\n\n", "⚠ '{0}' ARMA O DESLIGAMENTO DA SAÍDA: as tomadas do UPS podem cortar a energia de tudo o que está ligado.\n\n", "⚠ '{0}' ВЗВОДИТ ОТКЛЮЧЕНИЕ ВЫХОДА: розетки ИБП могут обесточить всё подключённое.\n\n", "⚠ '{0}' آؤٹ پٹ شٹ ڈاؤن مسلح کرتا ہے: UPS آؤٹ لیٹس تمام منسلک آلات کی بجلی کاٹ سکتے ہیں۔\n\n", "⚠ '{0}' MENGAKTIFKAN PEMADAMAN KELUARAN: stopkontak UPS dapat memutus daya semua yang terhubung.\n\n", "⚠ '{0}' AKTIVIERT DIE AUSGANGSABSCHALTUNG: die USV-Steckdosen können alles Angeschlossene stromlos machen.\n\n", "⚠ '{0}' は出力遮断を作動させます：UPSのコンセントは接続中の全機器への給電を断つ可能性があります。\n\n", "⚠ '{0}' आउटपुट बंद करणे सक्रिय करते: UPS आउटलेट जोडलेल्या सर्व उपकरणांची वीज तोडू शकतात.\n\n", "⚠ '{0}' అవుట్‌పుట్ షట్‌డౌన్ ఆర్మ్ చేస్తుంది: UPS అవుట్‌లెట్లు కనెక్ట్ అయిన అన్నింటికీ పవర్ కట్ చేయవచ్చు.\n\n", "⚠ '{0}' ÇIKIŞ KAPATMASINI DEVREYE ALIR: UPS prizleri bağlı her şeyin gücünü kesebilir.\n\n", "⚠ '{0}' வெளியீட்டு நிறுத்தத்தை இயக்குகிறது: UPS சாக்கெட்டுகள் இணைந்த அனைத்திற்கும் மின்சாரம் துண்டிக்கலாம்.\n\n", "⚠ '{0}' KÍCH HOẠT NGẮT ĐẦU RA: ổ cắm UPS có thể cắt điện mọi thứ đang kết nối.\n\n", "⚠ '{0}'은(는) 출력 차단을 작동시킵니다: UPS 콘센트가 연결된 모든 장치의 전원을 끊을 수 있습니다.\n\n" },
        ["set_write_ok"] = new[] { "Written and confirmed: {0} {1}.", "Scritto e confermato: {0} {1}.", "已写入并确认：{0} {1}。", "लिखा और पुष्टि: {0} {1}।", "Escrito y confirmado: {0} {1}.", "Écrit et confirmé : {0} {1}.", "كُتب وتأكد: {0} {1}.", "লেখা ও নিশ্চিত: {0} {1}।", "Gravado e confirmado: {0} {1}.", "Записано и подтверждено: {0} {1}.", "لکھا اور تصدیق: {0} {1}۔", "Ditulis dan dikonfirmasi: {0} {1}.", "Geschrieben und bestätigt: {0} {1}.", "書き込み・確認済み：{0} {1}。", "लिहिले व पुष्टी: {0} {1}.", "వ్రాసి నిర్ధారించబడింది: {0} {1}.", "Yazıldı ve doğrulandı: {0} {1}.", "எழுதி உறுதி: {0} {1}.", "Đã ghi và xác nhận: {0} {1}.", "기록 및 확인됨: {0} {1}." },
        ["set_write_rejected"] = new[] { "Firmware did NOT accept the write (current value: {0}).", "Il firmware NON ha accettato la scrittura (valore attuale: {0}).", "固件未接受写入（当前值：{0}）。", "फर्मवेयर ने लेखन स्वीकार नहीं किया (वर्तमान मान: {0})।", "El firmware NO aceptó la escritura (valor actual: {0}).", "Le firmware n'a PAS accepté l'écriture (valeur actuelle : {0}).", "لم يقبل البرنامج الثابت الكتابة (القيمة الحالية: {0}).", "ফার্মওয়্যার লেখা গ্রহণ করেনি (বর্তমান মান: {0})।", "O firmware NÃO aceitou a gravação (valor atual: {0}).", "Прошивка НЕ приняла запись (текущее значение: {0}).", "فرم ویئر نے لکھنا قبول نہیں کیا (موجودہ قدر: {0})۔", "Firmware TIDAK menerima penulisan (nilai saat ini: {0}).", "Firmware hat das Schreiben NICHT übernommen (aktueller Wert: {0}).", "ファームウェアが書き込みを受け付けませんでした（現在値：{0}）。", "फर्मवेअरने लेखन स्वीकारले नाही (सध्याचे मूल्य: {0}).", "ఫర్మ్‌వేర్ వ్రాతను అంగీకరించలేదు (ప్రస్తుత విలువ: {0}).", "Aygıt yazılımı yazmayı KABUL ETMEDİ (geçerli değer: {0}).", "ஃபார்ம்வேர் எழுத்தை ஏற்கவில்லை (தற்போதைய மதிப்பு: {0}).", "Firmware KHÔNG chấp nhận ghi (giá trị hiện tại: {0}).", "펌웨어가 쓰기를 수락하지 않음 (현재 값: {0})." },
        ["set_write_err"] = new[] { "Write error: {0}", "Errore scrittura: {0}", "写入错误：{0}", "लेखन त्रुटि: {0}", "Error de escritura: {0}", "Erreur d'écriture : {0}", "خطأ كتابة: {0}", "লেখার ত্রুটি: {0}", "Erro de gravação: {0}", "Ошибка записи: {0}", "لکھنے میں خرابی: {0}", "Galat tulis: {0}", "Schreibfehler: {0}", "書き込みエラー：{0}", "लेखन त्रुटी: {0}", "వ్రాత లోపం: {0}", "Yazma hatası: {0}", "எழுத்து பிழை: {0}", "Lỗi ghi: {0}", "쓰기 오류: {0}" },
        ["set_ups_notfound"] = new[] { "UPS not found", "UPS non trovato", "未找到 UPS", "UPS नहीं मिला", "SAI no encontrado", "Onduleur introuvable", "UPS غير موجود", "UPS পাওয়া যায়নি", "UPS não encontrado", "ИБП не найден", "UPS نہیں ملا", "UPS tidak ditemukan", "USV nicht gefunden", "UPSが見つかりません", "UPS सापडला नाही", "UPS కనబడలేదు", "UPS bulunamadı", "UPS கிடைக்கவில்லை", "Không tìm thấy UPS", "UPS를 찾을 수 없음" },
        ["lang_label"] = new[] { "Language (restart to apply)", "Lingua (riavviare per applicare)", "语言（重启后生效）", "भाषा (लागू करने हेतु पुनरारंभ)", "Idioma (reiniciar para aplicar)", "Langue (redémarrer pour appliquer)", "اللغة (أعد التشغيل للتطبيق)", "ভাষা (প্রয়োগে পুনরায় চালু)", "Idioma (reinicie para aplicar)", "Язык (перезапустите для применения)", "زبان (اطلاق کیلئے دوبارہ شروع کریں)", "Bahasa (mulai ulang untuk menerapkan)", "Sprache (Neustart erforderlich)", "言語（適用には再起動）", "भाषा (लागू करण्यासाठी रीस्टार्ट)", "భాష (వర్తించడానికి రీస్టార్ట్)", "Dil (uygulamak için yeniden başlat)", "மொழி (பயன்பட மறுதொடக்கம்)", "Ngôn ngữ (khởi động lại để áp dụng)", "언어 (적용하려면 재시작)" },
        ["lang_auto"] = new[] { "Auto (system)", "Auto (sistema)", "自动（系统）", "स्वतः (सिस्टम)", "Auto (sistema)", "Auto (système)", "تلقائي (النظام)", "স্বয়ংক্রিয় (সিস্টেম)", "Auto (sistema)", "Авто (система)", "خودکار (نظام)", "Otomatis (sistem)", "Auto (System)", "自動（システム）", "स्वयं (सिस्टम)", "ఆటో (సిస్టమ్)", "Otomatik (sistem)", "தானியங்கு (கணினி)", "Tự động (hệ thống)", "자동 (시스템)" },

        ["syn_grid"] = new[] { "Mains power", "Rete elettrica", "市电", "मुख्य बिजली", "Red eléctrica", "Réseau électrique", "الكهرباء الرئيسية", "মেইনস বিদ্যুৎ", "Rede elétrica", "Электросеть", "مینز بجلی", "Listrik PLN", "Stromnetz", "商用電源", "मुख्य वीज", "మెయిన్స్ విద్యుత్", "Şebeke elektriği", "மின்சார விநியோகம்", "Điện lưới", "상용 전원" },
        ["syn_devices"] = new[] { "Connected devices", "Dispositivi collegati", "已连接设备", "जुड़े उपकरण", "Dispositivos conectados", "Appareils connectés", "الأجهزة الموصولة", "সংযুক্ত ডিভাইস", "Dispositivos conectados", "Подключённые устройства", "منسلک آلات", "Perangkat terhubung", "Angeschlossene Geräte", "接続機器", "जोडलेली उपकरणे", "కనెక్ట్ చేసిన పరికరాలు", "Bağlı cihazlar", "இணைந்த சாதனங்கள்", "Thiết bị kết nối", "연결된 장치" },
        ["syn_absent"] = new[] { "ABSENT", "ASSENTE", "断电", "अनुपस्थित", "AUSENTE", "ABSENT", "منقطع", "অনুপস্থিত", "AUSENTE", "ОТСУТСТВУЕТ", "غائب", "PADAM", "AUSGEFALLEN", "停電", "अनुपस्थित", "లేదు", "YOK", "இல்லை", "MẤT ĐIỆN", "없음" },
        ["syn_runtime"] = new[] { "runtime {0} min", "autonomia {0} min", "续航 {0} 分钟", "बैकअप {0} मिनट", "autonomía {0} min", "autonomie {0} min", "زمن التشغيل {0} دقيقة", "ব্যাকআপ {0} মিনিট", "autonomia {0} min", "время {0} мин", "بیک اپ {0} منٹ", "cadangan {0} menit", "Laufzeit {0} Min", "稼働 {0} 分", "बॅकअप {0} मिनिटे", "బ్యాకప్ {0} నిమి", "süre {0} dk", "நேரம் {0} நிமி", "dự phòng {0} phút", "잔여 {0} 분" },
        ["syn_runtime_big"] = new[] { "⏱ runtime {0} min", "⏱ autonomia {0} min", "⏱ 续航 {0} 分钟", "⏱ बैकअप {0} मिनट", "⏱ autonomía {0} min", "⏱ autonomie {0} min", "⏱ زمن التشغيل {0} دقيقة", "⏱ ব্যাকআপ {0} মিনিট", "⏱ autonomia {0} min", "⏱ время {0} мин", "⏱ بیک اپ {0} منٹ", "⏱ cadangan {0} menit", "⏱ Laufzeit {0} Min", "⏱ 稼働 {0} 分", "⏱ बॅकअप {0} मिनिटे", "⏱ బ్యాకప్ {0} నిమి", "⏱ süre {0} dk", "⏱ நேரம் {0} நிமி", "⏱ dự phòng {0} phút", "⏱ 잔여 {0} 분" },
        ["syn_battv"] = new[] { "battery {0} V", "batteria {0} V", "电池 {0} V", "बैटरी {0} V", "batería {0} V", "batterie {0} V", "البطارية {0} V", "ব্যাটারি {0} V", "bateria {0} V", "батарея {0} В", "بیٹری {0} V", "baterai {0} V", "Akku {0} V", "バッテリー {0} V", "बॅटरी {0} V", "బ్యాటరీ {0} V", "pil {0} V", "மின்கலம் {0} V", "pin {0} V", "배터리 {0} V" },
        ["recharge_eta"] = new[] { "recharging ~{0} min to full", "ricarica ~{0} min al 100%", "充电中，约 {0} 分钟充满", "चार्जिंग ~{0} मिनट में पूर्ण", "cargando ~{0} min para el 100%", "recharge ~{0} min avant 100%", "جارٍ الشحن ~{0} دقيقة للاكتمال", "চার্জ হচ্ছে ~{0} মিনিটে পূর্ণ", "carregando ~{0} min até 100%", "зарядка ~{0} мин до 100%", "چارجنگ ~{0} منٹ میں مکمل", "mengisi ~{0} menit hingga penuh", "lädt, ~{0} Min bis voll", "充電中 約{0}分で満充電", "चार्जिंग ~{0} मिनिटांत पूर्ण", "ఛార్జింగ్ ~{0} నిమిషాల్లో పూర్తి", "şarj oluyor, dolmasına ~{0} dk", "சார்ஜ் ஆகிறது ~{0} நிமிடத்தில் முழுமை", "đang sạc ~{0} phút nữa đầy", "충전 중, 완충까지 ~{0}분" },
        ["syn_load"] = new[] { "load", "carico", "负载", "लोड", "carga", "charge", "الحمل", "লোড", "carga", "нагрузка", "لوڈ", "beban", "Last", "負荷", "लोड", "లోడ్", "yük", "சுமை", "tải", "부하" },

        ["tray_open"] = new[] { "Open dashboard", "Apri dashboard", "打开仪表板", "डैशबोर्ड खोलें", "Abrir panel", "Ouvrir le tableau de bord", "فتح اللوحة", "ড্যাশবোর্ড খুলুন", "Abrir painel", "Открыть панель", "ڈیش بورڈ کھولیں", "Buka dasbor", "Dashboard öffnen", "ダッシュボードを開く", "डॅशबोर्ड उघडा", "డాష్‌బోర్డ్ తెరువు", "Paneli aç", "டாஷ்போர்டை திற", "Mở bảng điều khiển", "대시보드 열기" },
        ["tray_exit"] = new[] { "Exit", "Esci", "退出", "बाहर निकलें", "Salir", "Quitter", "خروج", "প্রস্থান", "Sair", "Выход", "باہر نکلیں", "Keluar", "Beenden", "終了", "बाहेर पडा", "నిష్క్రమించు", "Çıkış", "வெளியேறு", "Thoát", "종료" },

        ["al_mains_lost"] = new[] { "UPS: mains power lost", "UPS: rete elettrica assente", "UPS：市电断电", "UPS: मुख्य बिजली गई", "SAI: red eléctrica perdida", "Onduleur : secteur perdu", "UPS: انقطعت الكهرباء", "UPS: মেইনস বিদ্যুৎ নেই", "UPS: rede elétrica perdida", "ИБП: пропало сетевое питание", "UPS: مینز بجلی منقطع", "UPS: listrik PLN padam", "USV: Netzausfall", "UPS：商用電源喪失", "UPS: मुख्य वीज गेली", "UPS: మెయిన్స్ పవర్ పోయింది", "UPS: şebeke elektriği kesildi", "UPS: மின்சாரம் துண்டிக்கப்பட்டது", "UPS: mất điện lưới", "UPS: 상용전원 상실" },
        ["al_on_battery"] = new[] { "On battery. {0}", "Sistema su batteria. {0}", "使用电池供电。{0}", "बैटरी पर। {0}", "Con batería. {0}", "Sur batterie. {0}", "على البطارية. {0}", "ব্যাটারিতে। {0}", "Na bateria. {0}", "На батарее. {0}", "بیٹری پر۔ {0}", "Pakai baterai. {0}", "Auf Akku. {0}", "バッテリー動作中。{0}", "बॅटरीवर. {0}", "బ్యాటరీపై. {0}", "Pilde. {0}", "மின்கலத்தில். {0}", "Chạy pin. {0}", "배터리 작동 중. {0}" },
        ["al_mains_back"] = new[] { "UPS: mains power restored", "UPS: rete elettrica ripristinata", "UPS：市电恢复", "UPS: मुख्य बिजली बहाल", "SAI: red eléctrica restaurada", "Onduleur : secteur rétabli", "UPS: عادت الكهرباء", "UPS: মেইনস বিদ্যুৎ ফিরেছে", "UPS: rede elétrica restaurada", "ИБП: сетевое питание восстановлено", "UPS: مینز بجلی بحال", "UPS: listrik PLN pulih", "USV: Netz wiederhergestellt", "UPS：商用電源復旧", "UPS: मुख्य वीज परत आली", "UPS: మెయిన్స్ పవర్ పునరుద్ధరణ", "UPS: şebeke elektriği geri geldi", "UPS: மின்சாரம் மீண்டது", "UPS: có điện lưới lại", "UPS: 상용전원 복구" },
        ["al_hib_sim"] = new[] { "UPS: SIMULATED hibernation", "UPS: ibernazione SIMULATA", "UPS：模拟休眠", "UPS: सिमुलेटेड हाइबरनेशन", "SAI: hibernación SIMULADA", "Onduleur : hibernation SIMULÉE", "UPS: إسبات محاكى", "UPS: সিমুলেটেড হাইবারনেশন", "UPS: hibernação SIMULADA", "ИБП: СИМУЛЯЦИЯ гибернации", "UPS: نقلی ہائبرنیشن", "UPS: hibernasi SIMULASI", "USV: SIMULIERTER Ruhezustand", "UPS：休止（シミュレーション）", "UPS: सिम्युलेटेड हायबरनेशन", "UPS: సిమ్యులేటెడ్ హైబర్నేషన్", "UPS: SİMÜLE hazırda bekletme", "UPS: சிமுலேட்டட் ஹைபர்நேட்", "UPS: ngủ đông MÔ PHỎNG", "UPS: 시뮬레이션 최대 절전" },
        ["al_hib"] = new[] { "UPS: hibernating now", "UPS: ibernazione in corso", "UPS：正在休眠", "UPS: हाइबरनेट हो रहा", "SAI: hibernando ahora", "Onduleur : hibernation en cours", "UPS: جارٍ الإسبات", "UPS: হাইবারনেট হচ্ছে", "UPS: hibernando agora", "ИБП: выполняется гибернация", "UPS: ہائبرنیٹ ہو رہا", "UPS: hibernasi sekarang", "USV: Ruhezustand wird ausgeführt", "UPS：休止実行中", "UPS: हायबरनेट होत आहे", "UPS: హైబర్నేట్ అవుతోంది", "UPS: hazırda bekletiliyor", "UPS: ஹைபர்நேட் ஆகிறது", "UPS: đang ngủ đông", "UPS: 최대 절전 진행 중" },
        ["al_hib_body"] = new[] { "Battery exhausted. {0}", "Batteria esaurita. {0}", "电池耗尽。{0}", "बैटरी समाप्त। {0}", "Batería agotada. {0}", "Batterie épuisée. {0}", "نفدت البطارية. {0}", "ব্যাটারি শেষ। {0}", "Bateria esgotada. {0}", "Батарея исчерпана. {0}", "بیٹری ختم۔ {0}", "Baterai habis. {0}", "Akku erschöpft. {0}", "バッテリー切れ。{0}", "बॅटरी संपली. {0}", "బ్యాటరీ అయిపోయింది. {0}", "Pil tükendi. {0}", "மின்கலம் தீர்ந்தது. {0}", "Pin cạn. {0}", "배터리 소진. {0}" },
        ["al_ups_prefix"] = new[] { "UPS: {0}", "UPS: {0}", "UPS：{0}", "UPS: {0}", "SAI: {0}", "Onduleur : {0}", "UPS: {0}", "UPS: {0}", "UPS: {0}", "ИБП: {0}", "UPS: {0}", "UPS: {0}", "USV: {0}", "UPS：{0}", "UPS: {0}", "UPS: {0}", "UPS: {0}", "UPS: {0}", "UPS: {0}", "UPS: {0}" },

        ["rs_no_mains"] = new[] { "mains power absent", "alimentazione di rete assente", "市电断电", "मुख्य बिजली अनुपस्थित", "red eléctrica ausente", "secteur absent", "الكهرباء منقطعة", "মেইনস বিদ্যুৎ নেই", "rede elétrica ausente", "нет сетевого питания", "مینز بجلی غائب", "listrik PLN padam", "Netz ausgefallen", "商用電源なし", "मुख्य वीज नाही", "మెయిన్స్ పవర్ లేదు", "şebeke elektriği yok", "மின்சாரம் இல்லை", "mất điện lưới", "상용전원 없음" },
        ["rs_charge_crit"] = new[] { "CRITICAL charge {0}% ≤ {1}%", "carica CRITICA {0}% ≤ {1}%", "电量危急 {0}% ≤ {1}%", "गंभीर चार्ज {0}% ≤ {1}%", "carga CRÍTICA {0}% ≤ {1}%", "charge CRITIQUE {0}% ≤ {1}%", "شحن حرج {0}% ≤ {1}%", "সংকটজনক চার্জ {0}% ≤ {1}%", "carga CRÍTICA {0}% ≤ {1}%", "КРИТИЧНЫЙ заряд {0}% ≤ {1}%", "نازک چارج {0}% ≤ {1}%", "daya KRITIS {0}% ≤ {1}%", "KRITISCHE Ladung {0}% ≤ {1}%", "残量が危険 {0}% ≤ {1}%", "गंभीर चार्ज {0}% ≤ {1}%", "క్రిటికల్ ఛార్జ్ {0}% ≤ {1}%", "KRİTİK şarj {0}% ≤ {1}%", "நெருக்கடி சார்ஜ் {0}% ≤ {1}%", "pin NGUY CẤP {0}% ≤ {1}%", "위험 충전 {0}% ≤ {1}%" },
        ["rs_charge"] = new[] { "charge {0}% ≤ {1}%", "carica {0}% ≤ {1}%", "电量 {0}% ≤ {1}%", "चार्ज {0}% ≤ {1}%", "carga {0}% ≤ {1}%", "charge {0}% ≤ {1}%", "الشحن {0}% ≤ {1}%", "চার্জ {0}% ≤ {1}%", "carga {0}% ≤ {1}%", "заряд {0}% ≤ {1}%", "چارج {0}% ≤ {1}%", "daya {0}% ≤ {1}%", "Ladung {0}% ≤ {1}%", "残量 {0}% ≤ {1}%", "चार्ज {0}% ≤ {1}%", "ఛార్జ్ {0}% ≤ {1}%", "şarj {0}% ≤ {1}%", "சார்ஜ் {0}% ≤ {1}%", "pin {0}% ≤ {1}%", "충전 {0}% ≤ {1}%" },
        ["rs_rt_crit"] = new[] { "CRITICAL runtime {0} min ≤ {1} min", "autonomia CRITICA {0} min ≤ {1} min", "续航危急 {0} 分 ≤ {1} 分", "गंभीर बैकअप {0} मि ≤ {1} मि", "autonomía CRÍTICA {0} min ≤ {1} min", "autonomie CRITIQUE {0} min ≤ {1} min", "زمن تشغيل حرج {0} د ≤ {1} د", "সংকটজনক ব্যাকআপ {0} মি ≤ {1} মি", "autonomia CRÍTICA {0} min ≤ {1} min", "КРИТИЧНОЕ время {0} мин ≤ {1} мин", "نازک بیک اپ {0} منٹ ≤ {1} منٹ", "cadangan KRITIS {0} mnt ≤ {1} mnt", "KRITISCHE Laufzeit {0} Min ≤ {1} Min", "稼働時間が危険 {0} 分 ≤ {1} 分", "गंभीर बॅकअप {0} मि ≤ {1} मि", "క్రిటికల్ బ్యాకప్ {0} నిమి ≤ {1} నిమి", "KRİTİK süre {0} dk ≤ {1} dk", "நெருக்கடி நேரம் {0} நிமி ≤ {1} நிமி", "thời gian NGUY CẤP {0} phút ≤ {1} phút", "위험 시간 {0}분 ≤ {1}분" },
        ["rs_rt"] = new[] { "runtime {0} min ≤ {1} min", "autonomia {0} min ≤ {1} min", "续航 {0} 分 ≤ {1} 分", "बैकअप {0} मि ≤ {1} मि", "autonomía {0} min ≤ {1} min", "autonomie {0} min ≤ {1} min", "زمن التشغيل {0} د ≤ {1} د", "ব্যাকআপ {0} মি ≤ {1} মি", "autonomia {0} min ≤ {1} min", "время {0} мин ≤ {1} мин", "بیک اپ {0} منٹ ≤ {1} منٹ", "cadangan {0} mnt ≤ {1} mnt", "Laufzeit {0} Min ≤ {1} Min", "稼働 {0} 分 ≤ {1} 分", "बॅकअप {0} मि ≤ {1} मि", "బ్యాకప్ {0} నిమి ≤ {1} నిమి", "süre {0} dk ≤ {1} dk", "நேரம் {0} நிமி ≤ {1} நிமி", "thời gian {0} phút ≤ {1} phút", "시간 {0}분 ≤ {1}분" },
        ["rs_overload"] = new[] { "overload {0}% ≥ {1}%", "sovraccarico {0}% ≥ {1}%", "过载 {0}% ≥ {1}%", "अधिभार {0}% ≥ {1}%", "sobrecarga {0}% ≥ {1}%", "surcharge {0}% ≥ {1}%", "حمل زائد {0}% ≥ {1}%", "অতিরিক্ত লোড {0}% ≥ {1}%", "sobrecarga {0}% ≥ {1}%", "перегрузка {0}% ≥ {1}%", "زیادہ لوڈ {0}% ≥ {1}%", "kelebihan beban {0}% ≥ {1}%", "Überlast {0}% ≥ {1}%", "過負荷 {0}% ≥ {1}%", "अतिभार {0}% ≥ {1}%", "ఓవర్‌లోడ్ {0}% ≥ {1}%", "aşırı yük {0}% ≥ {1}%", "மிகைச்சுமை {0}% ≥ {1}%", "quá tải {0}% ≥ {1}%", "과부하 {0}% ≥ {1}%" },
        ["err_notfound"] = new[] { "UPS not found: check the USB cable.", "UPS non trovato: controllare il cavo USB.", "未找到UPS：请检查USB线。", "UPS नहीं मिला: USB केबल जाँचें।", "SAI no encontrado: revise el cable USB.", "Onduleur introuvable : vérifiez le câble USB.", "UPS غير موجود: افحص كابل USB.", "UPS পাওয়া যায়নি: USB কেবল দেখুন।", "UPS não encontrado: verifique o cabo USB.", "ИБП не найден: проверьте USB-кабель.", "UPS نہیں ملا: USB کیبل چیک کریں۔", "UPS tidak ditemukan: periksa kabel USB.", "USV nicht gefunden: USB-Kabel prüfen.", "UPSが見つかりません：USBケーブルを確認。", "UPS सापडला नाही: USB केबल तपासा.", "UPS కనబడలేదు: USB కేబుల్ చూడండి.", "UPS bulunamadı: USB kablosunu kontrol edin.", "UPS கிடைக்கவில்லை: USB கேபிளை சரிபார்க்கவும்.", "Không tìm thấy UPS: kiểm tra cáp USB.", "UPS를 찾을 수 없음: USB 케이블 확인." },

        ["st_line"] = new[] { "{0} | charge {1}% | runtime {2} min | load {3}% ({4} W) | in {5} V | out {6} V | batt {7} V", "{0} | carica {1}% | autonomia {2} min | carico {3}% ({4} W) | in {5} V | out {6} V | batt {7} V", "{0} | 电量 {1}% | 续航 {2} 分 | 负载 {3}% ({4} W) | 入 {5} V | 出 {6} V | 电池 {7} V", "{0} | चार्ज {1}% | बैकअप {2} मि | लोड {3}% ({4} W) | इन {5} V | आउट {6} V | बैट {7} V", "{0} | carga {1}% | autonomía {2} min | carga {3}% ({4} W) | ent {5} V | sal {6} V | bat {7} V", "{0} | charge {1}% | autonomie {2} min | charge {3}% ({4} W) | ent {5} V | sor {6} V | bat {7} V", "{0} | الشحن {1}% | التشغيل {2} د | الحمل {3}% ({4} W) | دخل {5} V | خرج {6} V | بطارية {7} V", "{0} | চার্জ {1}% | ব্যাকআপ {2} মি | লোড {3}% ({4} W) | ইন {5} V | আউট {6} V | ব্যাট {7} V", "{0} | carga {1}% | autonomia {2} min | carga {3}% ({4} W) | ent {5} V | saí {6} V | bat {7} V", "{0} | заряд {1}% | время {2} мин | нагрузка {3}% ({4} Вт) | вх {5} В | вых {6} В | бат {7} В", "{0} | چارج {1}% | بیک اپ {2} منٹ | لوڈ {3}% ({4} W) | اِن {5} V | آؤٹ {6} V | بیٹ {7} V", "{0} | daya {1}% | cadangan {2} mnt | beban {3}% ({4} W) | in {5} V | out {6} V | bat {7} V", "{0} | Ladung {1}% | Laufzeit {2} Min | Last {3}% ({4} W) | Ein {5} V | Aus {6} V | Akku {7} V", "{0} | 残量 {1}% | 稼働 {2} 分 | 負荷 {3}% ({4} W) | 入 {5} V | 出 {6} V | 電池 {7} V", "{0} | चार्ज {1}% | बॅकअप {2} मि | लोड {3}% ({4} W) | इन {5} V | आउट {6} V | बॅट {7} V", "{0} | ఛార్జ్ {1}% | బ్యాకప్ {2} నిమి | లోడ్ {3}% ({4} W) | ఇన్ {5} V | అవుట్ {6} V | బ్యాట్ {7} V", "{0} | şarj {1}% | süre {2} dk | yük {3}% ({4} W) | giriş {5} V | çıkış {6} V | pil {7} V", "{0} | சார்ஜ் {1}% | நேரம் {2} நிமி | சுமை {3}% ({4} W) | இன் {5} V | அவுட் {6} V | பேட் {7} V", "{0} | pin {1}% | dự phòng {2} phút | tải {3}% ({4} W) | vào {5} V | ra {6} V | ắc quy {7} V", "{0} | 충전 {1}% | 시간 {2}분 | 부하 {3}% ({4} W) | 입력 {5} V | 출력 {6} V | 배터리 {7} V" },

        ["param_LowVoltageTransfer"] = new[] { "Low transfer threshold", "Soglia trasferimento bassa", "低压切换阈值", "निम्न ट्रांसफर सीमा", "Umbral de transferencia bajo", "Seuil de transfert bas", "عتبة التحويل الدنيا", "নিম্ন ট্রান্সফার সীমা", "Limite de transferência baixo", "Нижний порог перехода", "کم ٹرانسفر حد", "Ambang transfer rendah", "Untere Transferschwelle", "低電圧切替しきい値", "कमी ट्रान्सफर मर्यादा", "తక్కువ ట్రాన్స్‌ఫర్ పరిమితి", "Alt transfer eşiği", "குறைந்த மாற்று வரம்பு", "Ngưỡng chuyển thấp", "저전압 전환 임계값" },
        ["param_HighVoltageTransfer"] = new[] { "High transfer threshold", "Soglia trasferimento alta", "高压切换阈值", "उच्च ट्रांसफर सीमा", "Umbral de transferencia alto", "Seuil de transfert haut", "عتبة التحويل العليا", "উচ্চ ট্রান্সফার সীমা", "Limite de transferência alto", "Верхний порог перехода", "زیادہ ٹرانسفر حد", "Ambang transfer tinggi", "Obere Transferschwelle", "高電圧切替しきい値", "उच्च ट्रान्सफर मर्यादा", "అధిక ట్రాన్స్‌ఫర్ పరిమితి", "Üst transfer eşiği", "உயர் மாற்று வரம்பு", "Ngưỡng chuyển cao", "고전압 전환 임계값" },
        ["param_Test"] = new[] { "Battery test command", "Comando test batteria", "电池测试命令", "बैटरी परीक्षण आदेश", "Comando de prueba de batería", "Commande de test batterie", "أمر اختبار البطارية", "ব্যাটারি পরীক্ষা কমান্ড", "Comando de teste da bateria", "Команда теста батареи", "بیٹری ٹیسٹ کمانڈ", "Perintah uji baterai", "Akkutest-Befehl", "バッテリーテスト指令", "बॅटरी चाचणी आदेश", "బ్యాటరీ పరీక్ష కమాండ్", "Pil testi komutu", "மின்கல சோதனை கட்டளை", "Lệnh kiểm tra pin", "배터리 테스트 명령" },
        ["param_AudibleAlarmControl"] = new[] { "Audible alarm (2=on 3=off)", "Allarme acustico (2=on 3=off)", "声音警报（2=开 3=关）", "श्रव्य अलार्म (2=चालू 3=बंद)", "Alarma sonora (2=sí 3=no)", "Alarme sonore (2=on 3=off)", "إنذار صوتي (2=تشغيل 3=إيقاف)", "শ্রবণ অ্যালার্ম (2=চালু 3=বন্ধ)", "Alarme sonoro (2=lig 3=desl)", "Звуковой сигнал (2=вкл 3=выкл)", "آواز الارم (2=آن 3=آف)", "Alarm suara (2=nyala 3=mati)", "Signalton (2=ein 3=aus)", "ブザー（2=有効 3=無効）", "ध्वनी अलार्म (2=चालू 3=बंद)", "శబ్ద అలారం (2=ఆన్ 3=ఆఫ్)", "Sesli alarm (2=açık 3=kapalı)", "ஒலி எச்சரிக்கை (2=இயக்கு 3=நிறுத்து)", "Chuông báo (2=bật 3=tắt)", "경고음 (2=켬 3=끔)" },
        ["param_DelayBeforeShutdown"] = new[] { "Output shutdown delay", "Ritardo spegnimento uscita", "输出关机延时", "आउटपुट शटडाउन विलंब", "Retardo de apagado de salida", "Délai de coupure de sortie", "مهلة إيقاف الخرج", "আউটপুট শাটডাউন বিলম্ব", "Atraso de desligamento da saída", "Задержка отключения выхода", "آؤٹ پٹ شٹ ڈاؤن تاخیر", "Tunda pemadaman keluaran", "Ausgangs-Abschaltverzögerung", "出力遮断遅延", "आउटपुट बंद विलंब", "అవుట్‌పుట్ షట్‌డౌన్ ఆలస్యం", "Çıkış kapatma gecikmesi", "வெளியீட்டு நிறுத்த தாமதம்", "Trễ ngắt đầu ra", "출력 차단 지연" },
        ["param_DelayBeforeReboot"] = new[] { "Output reboot delay", "Ritardo riavvio uscita", "输出重启延时", "आउटपुट रीबूट विलंब", "Retardo de reinicio de salida", "Délai de redémarrage de sortie", "مهلة إعادة تشغيل الخرج", "আউটপুট রিবুট বিলম্ব", "Atraso de reinício da saída", "Задержка перезапуска выхода", "آؤٹ پٹ ری بوٹ تاخیر", "Tunda mulai ulang keluaran", "Ausgangs-Neustartverzögerung", "出力再起動遅延", "आउटपुट रीबूट विलंब", "అవుట్‌పుట్ రీబూట్ ఆలస్యం", "Çıkış yeniden başlatma gecikmesi", "வெளியீட்டு மறுதொடக்க தாமதம்", "Trễ khởi động lại đầu ra", "출력 재시작 지연" },
        ["param_WarningCapacityLimit"] = new[] { "Capacity warning threshold", "Soglia avviso capacità", "容量警告阈值", "क्षमता चेतावनी सीमा", "Umbral de aviso de capacidad", "Seuil d'alerte de capacité", "عتبة تحذير السعة", "ক্ষমতা সতর্কতা সীমা", "Limite de aviso de capacidade", "Порог предупреждения ёмкости", "گنجائش انتباہ حد", "Ambang peringatan kapasitas", "Kapazitätswarnschwelle", "容量警告しきい値", "क्षमता इशारा मर्यादा", "కెపాసిటీ హెచ్చరిక పరిమితి", "Kapasite uyarı eşiği", "கொள்ளளவு எச்சரிக்கை வரம்பு", "Ngưỡng cảnh báo dung lượng", "용량 경고 임계값" },
        ["param_DelayBeforeStartup"] = new[] { "Output startup delay", "Ritardo avvio uscita", "输出启动延时", "आउटपुट स्टार्टअप विलंब", "Retardo de arranque de salida", "Délai de démarrage de sortie", "مهلة بدء الخرج", "আউটপুট স্টার্টআপ বিলম্ব", "Atraso de partida da saída", "Задержка запуска выхода", "آؤٹ پٹ اسٹارٹ اپ تاخیر", "Tunda mulai keluaran", "Ausgangs-Startverzögerung", "出力起動遅延", "आउटपुट सुरूवात विलंब", "అవుట్‌పుట్ స్టార్టప్ ఆలస్యం", "Çıkış başlatma gecikmesi", "வெளியீட்டு தொடக்க தாமதம்", "Trễ khởi động đầu ra", "출력 시작 지연" },
    };
}
